### ISSUE TITLE
Incorrect Links: Duraguard Storm Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#101]
Incorrect links on the Duraguard Storm Door page:

Link Privacy Glass button below to URL with trailing slash:  https://provia.proviaserver-v2.com/doors/privacy-glass/
![image](https://user-images.githubusercontent.com/78490468/159337832-939bbadc-b667-4c76-bf44-48f2e41ce96a.png)

Link button below to Storm Door Technology page:  https://provia.proviaserver-v2.com/doors/technology/storm-door/
![image](https://user-images.githubusercontent.com/78490468/159337076-673d30f1-f405-4167-aeb0-fc8c5f25e64d.png)

**Comment by SeanIsAtWork** [comment]
These have been fixed
