### ISSUE TITLE
Mobile Menu - Door Brands links not working

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#102]
In the Mobile Menu, none of the door brands links work (Entry Doors, Patio Doors, Storm Doors):
![image](https://user-images.githubusercontent.com/78490468/159338693-477ff4a9-d10a-401e-94c1-4d597f0ce6e0.png)

![image](https://user-images.githubusercontent.com/78490468/159338751-fa0b9d27-f9f2-4cc3-bad6-3140b8f88887.png)

![image](https://user-images.githubusercontent.com/78490468/159338823-b4119f6f-af91-4500-9593-ade30037d547.png)

**Comment by SeanIsAtWork** [comment]
Links have been fixed
