### ISSUE TITLE
Patio Door Brands page issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#103]
Incorrect Link text (should be Endure, Aspect, ecoLite).  Also, remove the TM marks, they are already used higher on the page, no need for them in this chart.

![image](https://user-images.githubusercontent.com/78490468/159340046-0eaf9411-6f8a-465b-80c1-cd276bffa7d7.png)

Center PDF button on smaller screen resolutions (1024x768 and iPad)
![image](https://user-images.githubusercontent.com/78490468/159341831-4545c502-1d26-4171-a9fd-ccbe8ccf74a0.png)

Page styling not displaying properly on Edge browsers (large and small) and Chrome 1024x768, 1280x1024, 1600x1200 screen resolution:

![image](https://user-images.githubusercontent.com/78490468/159342006-b436bc32-fbd5-47c2-b701-308c5743cc96.png)

![image](https://user-images.githubusercontent.com/78490468/159342102-5360d28b-9adf-4e2a-beed-5adf343ffcb0.png)

![image](https://user-images.githubusercontent.com/78490468/159342171-87828657-c04c-4742-987a-2f90a3d88820.png)

**Comment by SeanIsAtWork** [comment]
Regarding the page not rendering properly on edge, it seems like this happens randomly on certain pages. Visiting the page some time later will sometimes have the page display as it should. Not sure what causes this. I'm going to make a separate issue for whats happening with pages on edge and close this one
