### ISSUE TITLE
Design Center: Palette Hover State

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#11]
We would like the first item in each palette to be hovered by default on load like this:
![palette-onhover-state](https://user-images.githubusercontent.com/95431522/144459537-fa14827f-a354-4b79-9f6b-f2846b7a7d54.JPG)

**Comment by ancaipen** [comment]
TI Wishlist code may be able to accomplish this, lower priority for now than other open items.  Start by opening ticket with TI wishlist and see if we can get direct feedback about code snippet to use.
