### ISSUE TITLE
Incorrect Link: Get Inspired

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#139]
Sean, can you fix the text link on the Get Inspired module across the site or do you need me to point out all instances where it appears on the page?  Need to add trailing slash to the text link:

![image](https://user-images.githubusercontent.com/78490468/159535486-931af550-c743-4895-9f19-c3178098140d.png)

**Comment by SeanIsAtWork** [comment]
I can fix that across the board




Sean Graham
Web/Graphic Designer | Strasburg Facility
[Logo]<https://www.provia.com/>
office: 330.852.4711
direct: 330.852.1559
www.provia.com<http://www.provia.com>
[Facebook icon]<https://www.facebook.com/ProViaProducts>  [LinkedIn icon] <https://www.linkedin.com/company/provia-door>   [Instagram icon] <https://www.instagram.com/proviaproducts/>   [Youtube icon] <https://www.youtube.com/user/proviadoors>   [Pinterest icon] <https://pinterest.com/proviaproducts/>

From: Angie Charles ***@***.***>
Sent: Tuesday, March 22, 2022 1:04 PM
To: ancaipen/Provia ***@***.***>
Cc: Subscribed ***@***.***>
Subject: [ancaipen/Provia] Incorrect Link: Get Inspired (Issue #139)


Sean, can you fix the text link on the Get Inspired module across the site or do you need me to point out all instances where it appears on the page? Need to add trailing slash to the text link:

[image]<https://user-images.githubusercontent.com/78490468/159535486-931af550-c743-4895-9f19-c3178098140d.png>
