### ISSUE TITLE
Aeris Patio Door CSS styling not showing

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#153]
CSS styling not showing:

![image](https://user-images.githubusercontent.com/78490468/159543965-be088be2-1945-451c-a6ba-dcb8b237d93c.png)

Add trailing slash to these URLs:
![image](https://user-images.githubusercontent.com/78490468/159544160-1b5fed36-fcf2-4829-baf7-81f97fe475d1.png)

![image](https://user-images.githubusercontent.com/78490468/159544949-f5d25e1d-c23d-426f-9f64-8dde7a577e5b.png)

**Comment by SeanIsAtWork** [comment]
#104
