### ISSUE TITLE
Siding Accessories

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#159]
https://provia.proviaserver-v2.com/siding/accessories/ 

1. Mobile - Coordinating Accessories paragraph needs some left/right padding.
![image](https://user-images.githubusercontent.com/30931503/159558424-bbc39a4c-29ab-4650-b1ee-ec2a993ed0e8.png)

2. Mobile - Some letters are overlapping on interactive house picture and popups of letters too close to the edge of the screen are opening off screen, causing a horizontal scroll on the page (issues in both Android & IPhone).  
![image](https://user-images.githubusercontent.com/30931503/159558849-76bf34c0-a5d1-4bb4-8756-5581ac52f725.png)

3. Mobile Horizontal - content is stretched wider than viewport.  
![image](https://user-images.githubusercontent.com/30931503/159559702-6afd1d55-fa95-4cfb-b5af-55bd53fea145.png)

**Comment by SeanIsAtWork** [comment]
Replaced hotspot widget with static image paired with stylized tabs

**Comment by ncaipen** [comment]
Thanks.  The only thing I noticed is that if you want to keep this as a popup you may want to change the image description.   
![image](https://user-images.githubusercontent.com/30931503/160447344-53ee5b7f-b428-4db9-b21e-071049280742.png)
