### ISSUE TITLE
Mobile Device (iOS Chrome 15, 14 and Safari): Main Door Galleries Page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#20]
These issues showed up on most versions of iPhone 12 & 13, for both Chrome and Safari:
 
Storm Door Gallery button doesn't fit on screen
![image](https://user-images.githubusercontent.com/78490468/159139144-131957cc-e915-4a2d-ac23-ba4d7ed15811.png)

Door Articles section - a lot of extra white space above section
![image](https://user-images.githubusercontent.com/78490468/159139260-6c6b001b-95f9-49fd-978a-46c631fbbfe0.png)

Door-Related Videos section - a lot of white space above and below section
![image](https://user-images.githubusercontent.com/78490468/159139354-45729543-b9ec-415d-b3dd-a2195a6747fe.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed

**Comment by PilotFish3447** [comment]
Hi Sean, there's now a giant space between the top photo and the door gallery tabs in mobile and the CSS isn't displaying correctly on any size.
![image](https://user-images.githubusercontent.com/78490468/159494306-8723e384-1f7b-4d94-b67f-13d660fabf33.png)
![image](https://user-images.githubusercontent.com/78490468/159494628-411c8efd-bbfb-4e86-975d-10b585700944.png)

**Comment by SeanIsAtWork** [comment]
This is in reference to issue #104, at random times certain styles arent being applied. This is not page specific. I was seeing the same thing you're seeing yesterday and 20 minutes later I checked again and it displayed as it should have. 

What browser are you seeing this on? I see this on microsoft edge but I can update the issue if this is happening across other browsers.
