### ISSUE TITLE
Siding Css Issues

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#203]
https://provia.proviaserver-v2.com/siding/ 

1. Mobile & Ipad- anchor arrow to guide to the first section appears below the fold on mobile and is cut off on IPad.  Consider moving up so user will see it on page load.  
![image](https://user-images.githubusercontent.com/30931503/159754845-cb011062-fe59-49ef-b7db-b1b820754b88.png)
![image](https://user-images.githubusercontent.com/30931503/159754969-25963730-7182-4e18-9b92-7d47d2da786a.png)

2. Mobile - you may want to reduce some of this white space.  Seems like a little too much space on IPad and Desktop as well.  
![image](https://user-images.githubusercontent.com/30931503/159755225-085466b0-63d9-43af-91ec-23ce99b1921c.png)

**Comment by SeanIsAtWork** [comment]
I made some edits but we'll probably leave this as it is
