### ISSUE TITLE
Mobile Device:  Craftsman Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#22]
https://provia.proviaserver-v2.com/doors/entry-doors/craftsman
Tested on versions of Chrome and Safari on iPhone 12 and 13 

Text runs over image
![image](https://user-images.githubusercontent.com/78490468/159139732-03e61beb-9228-4ab8-8235-1225439f3fc6.png)

A lot of extra space above Popular Craftsman Door Styles
![image](https://user-images.githubusercontent.com/78490468/159139896-01cba638-60f2-4609-9ca6-5c0649155df5.png)
 
Seems like a lot of extra space above Popular Finish Options
![image](https://user-images.githubusercontent.com/78490468/159139796-92ed8912-c8fd-40b2-a56b-5259668f5c1f.png)

Firefox, MAC and Windows desktop issue:  Increase padding on left side starting at Popular Craftsman-Style Doors section to match padding at top of page (see top section first screenshot below, rest of page looks like 2nd screenshot below)
![image](https://user-images.githubusercontent.com/78490468/159140335-b419fd00-9b13-4319-8d20-5f6b96997c8b.png)

![image](https://user-images.githubusercontent.com/78490468/159140363-92129416-3f53-45e1-a141-358494e3ad3d.png)

**Comment by SeanIsAtWork** [comment]
- the padding on these sections has been fixed across all 4 architectural styles 
- the overlapping of the text and products overlapping has been fixed
