### ISSUE TITLE
Fieldstone CSS Issues

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#226]
https://provia.proviaserver-v2.com/stone/fieldstone/

1.  Mobile - I know you adjusted this section, but now some profiles are in columns of two and others are in one.  I would adjust for consistency.  This does look much better in tablet version now.  
![image](https://user-images.githubusercontent.com/30931503/159976749-8246c2e4-252c-4451-94f3-67a70351fe9f.png)

**Comment by SeanIsAtWork** [comment]
I mustve been in the middle of adjusting this when you checked this page, on 768px > theyre all stacked on top of each other and not in columns.

**Comment by ncaipen** [comment]
Yep you're right this looks good on the more recent pages I've looked at.
