### ISSUE TITLE
Internet Explorer:  Many Design Issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#23]
Internet Explorer represents just 0.41% of your users, so you'll need to decide whether to devote time to resolving the many issues in this browser. 

![image](https://user-images.githubusercontent.com/78490468/159141649-162ec322-82a9-4000-aa4c-fb717be8e014.png)

![image](https://user-images.githubusercontent.com/78490468/159141662-7b0b70e1-eb9a-4dae-8b95-f845d5e52363.png)

![image](https://user-images.githubusercontent.com/78490468/159141717-c741900b-1ba0-4612-bcb3-b24f1cd74fac.png)

**Comment by SeanIsAtWork** [comment]
Seems like elementor dropped support for internet explorer at the end of 2021 https://developers.elementor.com/elementor-dropping-support-ie/
