### ISSUE TITLE
iFrame Generator Code - Vinyl Soffit - Remove separate brands 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#233]
Aaron, please update the Vinyl Soffit iframe code - we only need one pointing to this page:  https://provia.proviaserver-v2.com/siding/vinyl-soffit/

The individual brands have become tabs on that vinyl soffit page - no need for separate iframes referencing Woodhaven, HeartTech, Beaded/Wainscot or Universal - remove those from the right-hand drop-down.
![image](https://user-images.githubusercontent.com/78490468/160010972-ccb8bd84-70a3-4549-896a-e96b14d56dfd.png)

**Comment by ancaipen** [comment]
This selection has been updated to only include the landing page: Vinyl Soffit
