### ISSUE TITLE
iFrame generation code - New URL for Metal Roofing

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#234]
Hi Aaron, please update the metal roofing iframe generator code to go to this page: https://provia.proviaserver-v2.com/metal-roofing/
URL was changed this week.

<iframe id="provia_iframe" src="https://provia.proviaserver-v2.com/roofing?iframe=true&font=default&fontsize=default&username=" width="100%" style="overflow:hidden;width:100%" frameborder="0" scrolling="no"></iframe>
<script type="text/javascript" src="https://provia.proviaserver-v2.com/wp-content//plugins/provia-iframe/scripts/iframe/proviaResize.js"></script>

**Comment by ancaipen** [comment]
This has been updated.
