### ISSUE TITLE
Blog CSS - Main Blog Index page  

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#235]
In 1024x768 (Chrome, Edge, Firefox), add left-hand padding to the text under Design Quizzes (or center the text):
![image](https://user-images.githubusercontent.com/78490468/160132458-a979798d-f708-4226-b2aa-3239454278ec.png)

Padding also needed for mobile:
![image](https://user-images.githubusercontent.com/78490468/160136345-fdee93b2-b4e6-4f7c-82f7-b075054e7fd4.png)

On Samsung:
![image](https://user-images.githubusercontent.com/78490468/160136439-ffc8d57b-ce8d-4ef7-89b4-7511fb35aa09.png)

On iPad:
![image](https://user-images.githubusercontent.com/78490468/160136862-dbdca2c0-b5a9-4e64-959a-75764e3f96a9.png)

**Comment by SeanIsAtWork** [comment]
We're just removing this section from the blog landing page
