### ISSUE TITLE
NCMA Anchor Issues

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#243]
1.  The top of the NCMA section is being cut off by the sticky header when using the anchor link from the main menu.  I have used this solution in the past to fix this issue if it helps -> https://wp-pagebuilderframework.com/sticky-header-overlaps-anchor-elementor/
![image](https://user-images.githubusercontent.com/30931503/160160200-8ace0c0d-bc00-4b58-80a9-1f0e69a891f2.png)

**Comment by SeanIsAtWork** [comment]
This is so helpful, thanks!
