### ISSUE TITLE
Add text links: Blog Article - Soft & Charming 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#257]
On this page: https://provia.proviaserver-v2.com/category/design/soft-charming-house-exterior-color-combinations/
Add text links below to respective product pages:
![image](https://user-images.githubusercontent.com/78490468/160192629-66e69673-bae4-49e6-aa8e-3ffc44e1877c.png)

**Comment by SeanIsAtWork** [comment]
We're not going to link to the product pages, and these really should be products but we'll revisit how we call out products in situations like these later on
