### ISSUE TITLE
Add text links:  Blog Article - Lively & Adventurous

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#259]
On this page: https://provia.proviaserver-v2.com/category/design/lively-adventurous-house-exterior-color-ideas/

Add additional category links on this article for:  Doors, Siding, Stone, Roofing 
![image](https://user-images.githubusercontent.com/78490468/160194491-2337f8fd-a5b4-4255-b031-e90cedb145db.png)

Add text links below to respective product pages:
![image](https://user-images.githubusercontent.com/78490468/160193449-8687b348-b534-474f-8939-ef8112e3d93f.png)

**Comment by SeanIsAtWork** [comment]
I think Jen was careful about which articles she added product categories to so I'm going to leave this as it is
