### ISSUE TITLE
Door Gallery page:  ProVia video descriptions in 1024x768 screen resolution

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#26]
On the main Door Gallery page, the longer ProVia video descriptions are wrapping onto a 2nd line and getting cut off:

![image](https://user-images.githubusercontent.com/78490468/159143245-a3c2d162-5c45-4914-8857-988de31d3bf9.png)

**Comment by SeanIsAtWork** [comment]
The title of each video now is restricted to one line
