### ISSUE TITLE
Add Text Links, Center Images:  Blog Article - Elegant & Stylish 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#260]
On this page: https://provia.proviaserver-v2.com/category/design/elegant-stylish-colors-for-home-exteriors/
Add text links below to respective product pages:
![image](https://user-images.githubusercontent.com/78490468/160195475-08311ad3-80a6-4992-a98a-db76b52662e0.png)

Center the top two images (for iPad)?
![image](https://user-images.githubusercontent.com/78490468/160195797-f6413a06-1a1d-4a31-9a13-c805e02cb0eb.png)

**Comment by SeanIsAtWork** [comment]
I'll leave this left justified
