### ISSUE TITLE
Grout Visualizer Like Button not working

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#287]
1.  The like button heart isn't working correctly since the IFrame change to optimize this section.  
![image](https://user-images.githubusercontent.com/30931503/160441676-6e483c9d-bfa9-48e5-94a4-7602db734453.png)

**Comment by ancaipen** [comment]
This bug has been fixed.  Update iframe javascript contained the same css ids which was causing the click event to not fire.  Now I see that the image has been selected when clicked:

![image](https://user-images.githubusercontent.com/43222107/160830385-1fc80778-de00-46b0-8804-e7b22403bc11.png)
