### ISSUE TITLE
Victorian House image in thumbnail

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#293]
On the door and window home architecture pages, did you want to update the Victorian home image in the thumbnails at the bottoms of the pages to match the new image at the top of the door and window Victorian Home pages?  

![image](https://user-images.githubusercontent.com/78490468/160853800-ac5ee2d6-571a-4e69-938a-84c7fddb3c3f.png)

**Comment by PilotFish3447** [comment]
On the Windows Architectural Home pages, the new Victorian home image isn't showing up in that particular module (though it is showing up on other window pages) -- I checked multiple devices to be sure it's not a caching issue: https://provia.proviaserver-v2.com/windows/modern/
![image](https://user-images.githubusercontent.com/78490468/160932084-4bc1ce4c-2560-475a-854a-84b281375192.png)

**Comment by SeanIsAtWork** [comment]
Oops, had a different shortcode for the window pages
