### ISSUE TITLE
Mobile Menu:  My Portfolio

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#300]
When you change the name of My Portfolio in the design, be sure to update it in the Mobile Menu as well.
![image](https://user-images.githubusercontent.com/78490468/160883649-a0c2b26a-2918-4d40-8f71-645dec246b23.png)

**Comment by SeanIsAtWork** [comment]
We aren't changing the name of my portfolio to anything else, maybe you're thinking of the "project builder" being renamed to "my vision board"?

**Comment by PilotFish3447** [comment]
Duh, yeah.  I misunderstood that email.  Thanks.
