### ISSUE TITLE
Mobile menu:  Non-trailing slash

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#303]
We need to update all the links in the mobile menu to have the trailing slash /.  I ran a site audit from BrightEdge and it picked up the non-trailing slash pages as 301 redirects, which we don't want.

**Comment by SeanIsAtWork** [comment]
I just checked the menu structure I'm using for the mobile menu and all of the navigation links have trailing slashes. Do we have specifics on which ones are showing up?

**Comment by PilotFish3447** [comment]
> I just checked the menu structure I'm using for the mobile menu and all of the navigation links have trailing slashes. Do we have specifics on which ones are showing up?

I think Natalee beat you to this - I'd assigned it to her.  I just checked and it looks like they all have trailing slash now.  I'll re-run the BrightEdge site audit before our meeting tomorrow to see if that took care of all the ones I was seeing today.  Thanks!

**Comment by ncaipen** [comment]
No, I didn't do anything with this.....

**Comment by SeanIsAtWork** [comment]
I must've added them wherever I could when I updated the structure yesterday

**Comment by PilotFish3447** [comment]
I'm going to re-run the BrightEdge report now - it'll show us any remaining URL issues - hopefully we'll be able to pinpoint them as being in the mobile menu.  If not, then we may have to wait till after site launch and then run a Screaming Frog report.
