### ISSUE TITLE
Performance Weaknesses and GT Metrix Reporting

### ISSUE THREAD

**Issue by ncaipen** [ancaipen/Provia#306]
I am attaching the original spreadsheet that Angie ran from BrightEdge.  I have filtered the Slow Response Time tab and ran GT Metrix reporting for any site that took longer than 5 seconds to load.  You will see on the spreadsheet that the overall grade is included.  A few pages took too long to load and could not be analyzed by GT Metrix.  You may want to prioritize the pages with the worst grades or pages that couldn't be tested because of slow load times first.  The zip file attached includes the corresponding reports.  

[GTmetrix-pagespeed-report.zip](https://github.com/ancaipen/Provia/files/8409803/GTmetrix-pagespeed-report.zip) 

[Slow Response Time-Page Size Issues-3-18-22-1.xlsx](https://github.com/ancaipen/Provia/files/8409823/Slow.Response.Time-Page.Size.Issues-3-18-22-1.xlsx)

**Comment by SeanIsAtWork** [comment]
I'm assigning @jenkline to this as well

**Comment by jenkline** [comment]
I used the Chrome extension WebPageTest and ran some of these pages through this as well. It looks like js and css are a huge contributing factor in the load times. In looking at the Performance plugin in Wordpress, it looks like html, js, and css all have minify selected, but at the very top of that section, there is a box that can be checked to enable minify, and that is currently not checked. Would it help to check that, or would that potentially mess some things up? Also, page cacheing looks like it is turned off in the Performance tool. I wonder if it would be helpful to turn that on prior to having employees test the site? Thoughts?
