### ISSUE TITLE
Mobile Menu:  Account button in iPad, iPhone

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#307]
Not sure if you want the Account nav button to line up this way on iPad and iPhone or if it should be flush left with the rest of the white buttons.
![image](https://user-images.githubusercontent.com/78490468/161565348-1cb35a25-e735-4c54-8f60-f9a3d454b9d8.png)

**Comment by SeanIsAtWork** [comment]
invisible icons were creating this space but theyre now visible
