### ISSUE TITLE
WTB not working

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#309]
WTB isn't working - when input zip code and  select the product type and dealer type, no results are showing up for any product. Also, when I click on the "List and Map" or "List Only" buttons, I get a 404 Error.
![image](https://user-images.githubusercontent.com/78490468/161588423-7762fd36-6d91-477f-b3be-fcba4da7007f.png)

**Comment by ancaipen** [comment]
This has been fixed.  I updated the code to use the new URL and the search above now appears to be working as expected.  

![image](https://user-images.githubusercontent.com/43222107/161764142-4f709b4b-57b2-4708-bff8-ef725dc1d9f0.png)
