### ISSUE TITLE
Broken/Incorrect Links: Architectural Style Homes on Main Entry Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#31]
The Architectural homes section on the main Entry Door page:
1. Craftsman link does not work (404 error)
2. The Victorian link goes to the Colonial page and the Colonial link goes to the Victorian page
Suggest you swap this module with the one on the Craftsman door page, which works correctly.
 
![image](https://user-images.githubusercontent.com/78490468/159174820-352946f2-a3ad-4157-ab8c-69acca9156bd.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed
