### ISSUE TITLE
Privacy Page responsive issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#310]
On a 1024x768 screen and on iPad, the text column is too narrow:
![image](https://user-images.githubusercontent.com/78490468/161608479-07c29d4d-9ba0-41ed-8d3a-d9992d20a9aa.png)
![image](https://user-images.githubusercontent.com/78490468/161608824-2b1e9efb-e283-4b1f-bf01-eb7a22b9e705.png)

**Comment by plaugs** [comment]
fixed
