### ISSUE TITLE
Text editor uses absolute URLs.

### ISSUE THREAD

**Issue by plaugs** [ancaipen/Provia#314]
When editing any text, wordpress uses absolute URLS in everything. Can we change this by default? This is not urgent, just something I know has created problems with links for me. 

example:
Url wordpress uses: https://provia.proviaserver-v2.com/doors/storm-doors/spectrum/
Url should be: /doors/storm-doors/spectrum/

Here is an article I found on the issue:
https://stackoverflow.com/questions/17187437/relative-urls-in-wordpress

**Comment by PilotFish3447** [comment]
I agree - it would be better for SEO to use relative links.

**Comment by ancaipen** [comment]
@ncaipen - I think this is the default functionality in wordpress, but I'll ask Natalee if this is possible.  We run a script to update these links to the correct domain when we go-live so that won't be an issue, but I'm not sure about making them relative.
