### ISSUE TITLE
Roofing text links on a few pages broken

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#315]
Fix link on Contact Us to metal roofing page:
![image](https://user-images.githubusercontent.com/78490468/161797145-7e9f36b7-2845-4415-8dbd-c2519443b574.png)
Fix text link on Warranty page:
![image](https://user-images.githubusercontent.com/78490468/161797721-709aa36b-6dbb-4984-b91f-20360f3a230d.png)

**Comment by PilotFish3447** [comment]
These aren't fixed. Correct URL is /metal-roofing/

**Comment by plaugs** [comment]
woops, my bad. Fixing now. I should have double checked.

**Comment by plaugs** [comment]
fixed.
