### ISSUE TITLE
Broken/Incorrect Links: Sliding Patio Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#32]
The patio door brands module has broken links to the individual brand pages:

![image](https://user-images.githubusercontent.com/78490468/159175993-5cfc6182-49c2-47f3-89f9-ab3cb0f5157c.png)

The brand comparison on the Sliding Patio Door page has the incorrect brand names associated with the links (they all say Aeris):

![image](https://user-images.githubusercontent.com/78490468/159176068-240a4f9b-c755-4936-913c-f8d077a7959d.png)

**Comment by SeanIsAtWork** [comment]
These links have been fixed
