### ISSUE TITLE
Literature links not loading content in iFrame

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#325]
Links to PDFs are not loading the content properly in the iframe, see this page: https://www.pilotfishseo.com/signet-dealer-code/
![image](https://user-images.githubusercontent.com/78490468/163027712-0ef960fd-8b7d-451f-b531-635d5e0f35a2.png)
![image](https://user-images.githubusercontent.com/78490468/163027798-23b56d61-5b21-48fa-ae00-70e2a06b0da8.png)

**Comment by PilotFish3447** [comment]
Hide the whole section.

**Comment by PilotFish3447** [comment]
@SeanIsAtWork Sean said he would hide the catalog download sections from iFrames.

**Comment by ancaipen** [comment]
@SeanIsAtWork - Can this be closed?

**Comment by PilotFish3447** [comment]
@SeanIsAtWork - yes, I checked all the iframe test pages.  Looks good.  I'm closing it.
