### ISSUE TITLE
3D animations don't function as intended on iFrame

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#326]
The 3D animations don't function as intended on the iFrame:  https://www.pilotfishseo.com/signet-dealer-code/
When you click a letter, the door doesn't open up as intended.  Click "F" or "D" as an example.
![image](https://user-images.githubusercontent.com/78490468/163028449-e1463b0b-ae4f-4628-b0af-ce2e689ae054.png)

**Comment by plaugs** [comment]
This was a conscious choice to animate the door this way. Certain features such as "door edge" are represented via door cutaway.
