### ISSUE TITLE
Spacing Issues: Sliding Patio Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#33]
Same spacing issues as on main Entry Door page -- too much white space between some sections, especially on smaller screen resolutions (ie 1024x768 and smaller)

![image](https://user-images.githubusercontent.com/78490468/159176430-d2fbc09a-42ac-4c33-ab7e-6f377b61b3be.png)

Patio Video module - longer video descriptions wrapping over to a 2nd line and getting cut off in smaller screen resolutions (ie 1024x768 and smaller)

![image](https://user-images.githubusercontent.com/78490468/159176501-d2f86fad-8992-4b76-a641-abb53b8f840a.png)

**Comment by SeanIsAtWork** [comment]
I've adjusted the dividing lines across the board to take up less space on 1024 and smaller screen sizes.
