### ISSUE TITLE
Console MIME type errors

### ISSUE THREAD

**Issue by plaugs** [ancaipen/Provia#332]
See the console here: https://www.pilotfishseo.com/signet-dealer-code/

I am getting a strange MIME type error and not sure how to fix it. 
![mime-error](https://user-images.githubusercontent.com/831625/163425793-58b1fb0c-bc5b-4fd0-ae12-ab44cfda0716.JPG)

**Comment by ancaipen** [comment]
@plaugs - I can see the door through the iframe in chrome and firefox.  I'm wondering if this is a firewall issue?  I added an exception for this file in the firewall, there must be something in there that is getting caught.  Can you load the file url below and let me know if it works for you?  Thanks!

https://provia.proviaserver-v2.com/wp-content/uploads/verge3d/css/loading.min.css
