### ISSUE TITLE
Door/Window Configurator Bugs

### ISSUE THREAD

**Issue by ancaipen** [ancaipen/Provia#333]
As reported by Jen on 4.18.2022

- The configurator URL needs a web session appended to it
- The S&P value also needs added to the link in the Design Center
- The “Save to My Portfolio” button does not seem to be saving an image back to the My Configurations section of My Portfolio

**Comment by ancaipen** [comment]
@jenkline - I tested the door configurator and it appears that the web session is working for me.  Lets talk about this on Thursday, here are my testing results:

1. Logged in as user: oxbow
2. Navigated to design center and created new door configuration and saved to my portfolio:

![image](https://user-images.githubusercontent.com/43222107/164085662-8e3997cb-73f1-43e1-b098-f659581296ac.png)

3. Iframe look correct with user = 1 appended to code behind the scenes:

![image](https://user-images.githubusercontent.com/43222107/164085924-fd83b98d-1cf3-4c5b-b0e1-1e02c65e32c6.png)

4. Door configuration I created shows up corrected in My Configurations section:

![image](https://user-images.githubusercontent.com/43222107/164085321-b48b451d-a954-4a3d-a3e5-9e9860ffdacd.png)

5. After clicking on saved door configuration I can see session and pass appended to the URL, saved door loads successfully:

![image](https://user-images.githubusercontent.com/43222107/164086592-2eb81622-5b77-4503-837d-3632ccf927f1.png)

![image](https://user-images.githubusercontent.com/43222107/164086680-89fe9cad-3626-4564-b039-918f2b565321.png)

**Comment by ancaipen** [comment]
@jenkline - Also, I just thought of this, maybe your issue was caching?  I added the design center and my portfolio areas to be excluded from caching (as they should be anyway).  Let me know if that helps.

![image](https://user-images.githubusercontent.com/43222107/164087260-aa462f7b-deef-4da4-9707-6d6868b34d84.png)

**Comment by jenkline** [comment]
![image](https://user-images.githubusercontent.com/104006203/164264192-91d8def8-8951-4872-96a0-a1d95a455308.png)
For me now, when I configure something it is showing "saved" after I save it, but still not showing up in My Configurations. I tried clearing my cache and refreshing the page, but that didn't help. User name is Jkline. I can send the password if you still want to try logging in as me.

**Comment by ancaipen** [comment]
@jenkline 

I looked into this issue and you are right, I'm not seeing the response come back from EntryLink.  It does look like the userid is appended as I would expect (see below).  I'm also seeing the response in our database, but it looks like it is adding everything with a userid = 1.  Your userid = 6 which appears to be appended to the iframe url correctly.  I'll send this info to Brent.  

![image](https://user-images.githubusercontent.com/43222107/164445539-053b9f61-30f1-4d50-a640-c5acb8d6fe18.png)

I do see the data coming back from EntryLink, but the userid = 1, instead of 6.  

![image](https://user-images.githubusercontent.com/43222107/164445853-9665cb29-cdb1-4f62-a940-0fd634fd5b2d.png)

When I manually update the userid = 6 I see the tests I was working with in EntryLink come through to your account.  So it looks like the API is being called with the correct session and password, but the userid is set in correctly.    

![image](https://user-images.githubusercontent.com/43222107/164446387-9f05661b-08ef-41c0-a314-fee7ea149a77.png)

![image](https://user-images.githubusercontent.com/43222107/164446542-bf56557d-d501-45cd-be43-4ae3581cf289.png)

**Comment by ancaipen** [comment]
@jenkline - Brent's latest changes appear to have fixed the user issue above.  Please retest and let me know if we can close this issue.  Thanks!

**Comment by jenkline** [comment]
Yes, this works now under my login. Thanks!
