### ISSUE TITLE
Facebook button don't seem to be working with vision boards

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#336]
I tested a saved vision board on my Facebook page (to me only) and this is what it looks like:
![image](https://user-images.githubusercontent.com/104006203/164025966-fc476e21-c7d0-4bb9-88b9-942b7d3ed7d8.png)
The URL that the Facebook post links to looks like this, and eventually times out: https://provia.com/?imageurl=https%3A%2F%2Fprovia.proviaserver-v2.com%2Fwp-content%2Fuploads%2Fprovia-myprojects%2F6%2F20220419142008.png&fbclid=IwAR0Pgmc7q5hF9ZJnCuzULxFplD0FBuMbF-yJSkXJeZTuJ_ps3w5Kdd-ipJQ
I can't test Twitter because I don't have an account.

**Comment by ancaipen** [comment]
This feature is going to be tough to test until we go live because we need to use a verified account for your main domain provia.com.  I'll see if I can work around this on our test site, but this will need to be changed once we go live.  I already have an item in our go-live checklist to update this link and test upon go-live.

**Comment by ancaipen** [comment]
@jenkline - This issue is related to #342

**Comment by PilotFish3447** [comment]
@ancaipen  @jenkline I tested Twitter and it's working fine.  I'll remove Twitter from the headline of this item and leave this as Open so we can re-test after site goes live.

**Comment by ancaipen** [comment]
@SeanIsAtWork : Hi Sean, now that the Facebook app settings are working can you enable the Share buttons so I can update the facebook share code?

**Comment by SeanIsAtWork** [comment]
@ancaipen sure! I just commented out the styles so you can give it a shot now.

**Comment by ancaipen** [comment]
Ok great, thanks!  This now appears to be working.  

![image](https://user-images.githubusercontent.com/43222107/169294180-6dee394d-01ba-4ad1-a497-30d17337f4f9.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork @jenkline - Can this issue be closed?

**Comment by PilotFish3447** [comment]
@ancaipen @SeanIsAtWork @jenkline - I'm OK with closing this out, are you guys?  But, I'm going to create a new issue for "Make Facebook/Twitter buttons live on Vision Board" so we don't forget to do that before the site launches.  We don't want to do that while your employees are still testing.

**Comment by jenkline** [comment]
@ancaipen That sounds good to me

**Comment by ancaipen** [comment]
I'm closing this issue.  I have added a step to the go-live checklist about enabling this feature.
