### ISSUE TITLE
Vision Board Autosave

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#337]
When creating a vision board a user can navigate away from the page by closing it and lose their progress. To avoid this frustration we should add an autosave feature. Any autosaved board that has yet to be named can be named **Untitled Vision Board**

**Comment by ancaipen** [comment]
@SeanIsAtWork - Hi Sean, I agree and we talked about this previously.  I will add this once we close all remaining bugs.  I will mark this as an enhancement and circle back to it once the bugs are resolved.

**Comment by SeanIsAtWork** [comment]
@ancaipen I remember, but in mentioning this to Jerome he told us that he wants this for launch.

**Comment by ancaipen** [comment]
The basics of this feature have been added.  Auto-Save takes place every 2 min and is capped at a total of 10 saves.  If no project is selected the project name will be defaulted.

![image](https://user-images.githubusercontent.com/43222107/165522397-2f0daebd-6d5b-4c1c-8794-24d58b9f5de1.png)

**Comment by SeanIsAtWork** [comment]
Would we be able to have the autosave trigger after a user puts an image onto the canvas? Currently if you hang out on the vision board section a blank board will be saved to your portfolio.

**Comment by ancaipen** [comment]
Good news!  I was able to figure this out.  I made an edit to the functions.php and added the button below the form instead of using a custom social login option where we don't have access to change the ordering.  Take a look now and let me know if that looks correct.  Thanks!

![image](https://user-images.githubusercontent.com/43222107/166916305-17a77d7a-0863-4f4a-bece-849ab4506286.png)

**Comment by PilotFish3447** [comment]
@ancaipen @SeanIsAtWork - I re-tested this and it appears that the board doesn't auto-save till you have at least saved it once, ie put something on the board and named the board.  Then, when you go back and add/delete stuff it does auto-save from there on out - even when you leave the page.  Also, it did not auto-save a blank canvass.  If this is the expected functionality, we can close this out.
