### ISSUE TITLE
Connect w/ Facebook option on Register page doesn't work

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#342]
Wasn't able to register via Connect with Facebook option.  Tried on desktop and iPhone.
https://provia.proviaserver-v2.com/register/?return_provider=facebook&err=um_social_user_denied&ref=1
![image](https://user-images.githubusercontent.com/78490468/164510661-e0396635-6391-49dd-b8b2-f557d37766c3.png)

**Comment by ancaipen** [comment]
@plaugs @jenkline 

Hi Brian, Jen

It looks like we will need the provia.com facebook credentials to get this working.  Is this something you all can do?  Basically we need to create a facebook app (no coding needed) and create an app id and app secret.  Here are the instructions: 

https://docs.ultimatemember.com/article/20-social-login-facebook-app-setup

Let me know if this is something you want us to handle (we will need your provia.com credentials if so).  Thanks!

**Comment by ancaipen** [comment]
@jenkline @plaugs - Making sure you all saw this, I want to make sure we have this working by launch this week.  Thanks!

**Comment by plaugs** [comment]
I don't know what credentials you need. provia.com joomla login? I started making a new app via the instructions and I got this:

App ID: 505930647696013
App Secret:  (Will email this)

**Comment by ncaipen** [comment]
Thanks, Brian!  Can you please switch this out of development mode within the Facebook account?  

![image](https://user-images.githubusercontent.com/30931503/165571899-f8f782f6-b9a6-4d4d-9a2a-21984c45bf6e.png)

**Comment by plaugs** [comment]
Ok everything should be setup now... but I am getting an error.
![registererror](https://user-images.githubusercontent.com/831625/166002253-3d5ad790-e9b9-47d4-9cbe-e1b6549549ee.png)

Also don't know if this helps?
![registererror2](https://user-images.githubusercontent.com/831625/166002357-79243abd-cc36-4678-ab31-6782912f2e10.png)

**Comment by ncaipen** [comment]
Did the API key and secret key change with your updates or is that still the same?  This looks like the same error that we were getting before we had the API credentials set up.

**Comment by plaugs** [comment]
The key and secret are the same. There are dozens of API and Authorization settings in the Facebook app settings that I have no idea might be the issue. Aaron, or Natalee, please check those and see if it's even set up correctly.

**Comment by PilotFish3447** [comment]
@plaugs @ncaipen -- I was poking around Facebook to get Jen added as an admin and found an area where you get your domain verified.  It was blank, so I added in the website, but Facebook needs to verify it.  Maybe doing this might help with the issue? 

![image](https://user-images.githubusercontent.com/78490468/166325356-91cb8620-3271-4d21-b02b-114d68bdcee1.png)

**Comment by plaugs** [comment]
I am verified in the app dashboard 
https://developers.facebook.com/apps/505930647696013
![Capture](https://user-images.githubusercontent.com/831625/166485582-9d8407bc-6f8b-49db-82b6-b5ba753338cc.JPG)

**Comment by plaugs** [comment]
I found it here: https://business.facebook.com/settings/owned-domains
I added the script and verified

**Comment by plaugs** [comment]
This line might need to be added in the header of the new site:
<meta name="facebook-domain-verification" content="6rmy62ndt2q18o2f6mw72kyvddd5vu" />

**Comment by ncaipen** [comment]
Ultimate Member documentation indicates that the error we are getting is usually related to a caching issue.  I have opened a ticket with Sucuri first, then will contact Ultimate Member for additional support if needed.  It looks like someone has deleted the facebook link from the registration page though?  

![image](https://user-images.githubusercontent.com/30931503/166490544-7212f47a-a740-4466-8bc3-cb7a6b243480.png)

**Comment by plaugs** [comment]
I think this is added via an ultimate member plug-in. None of us deleted this.

**Comment by ancaipen** [comment]
As an update: Natalee has opened a ticket with Ultimate Member and completed the plugin deactivation test during off hours.  It doesn't appear that another plugin is causing this issue.  Ultimate Member support is still looking into this issue.  We will keep you posted on progress as we have more information.

This issue is related to #336

**Comment by ncaipen** [comment]
This is now working and pulling data from Facebook.  I think you will probably want to add additional styles to the screen that pops up that connects you with Facebook, but Ultimate Member has confirmed that this has to be done with CSS.  I was able to login successfully using my Facebook account and was forwarded to the Portfolio page after registration.

**Comment by PilotFish3447** [comment]
@jenkline @plaugs @SeanIsAtWork - I'm unable to re-test this because I'd already created a ProVia account using the same email as my Facebook login, so it gives me an error saying I already have an account - which is good.  Can you guys test to be sure you can register using Facebook?

**Comment by ncaipen** [comment]
If needed you can delete the account in the Users admin section to allow yourself to register again.  I deleted and added again several times when testing.

**Comment by ncaipen** [comment]
FYI - I also added a connect with Facebook button to the login screen as users will need that to continue logging in repeatedly with Facebook credentials.  Just tested this and it took me straight to the portfolio page.

**Comment by ncaipen** [comment]
Did you clear the Sucuri cache as well?  I just cleared it.  If not I would try again.

**Comment by PilotFish3447** [comment]
@ncaipen - OK, for whatever reason, it's still associating my Facebook account with my Pilot Fish email, even though I changed my  email in Facebook.  So, it won't let me register.  But, when I use Facebook to log into the site, it does let me do that, so it seems to be working.  But it takes me to this page when I click the Connect with Facebook button on the Login page -- is this where it should go?:
![image](https://user-images.githubusercontent.com/78490468/169115452-6c569aa8-d53a-43ed-acd6-17faf292e37a.png)

**Comment by PilotFish3447** [comment]
@ncaipen - I was hoping any weird caching issues would be resolved overnight, but when I tried to register again this morning using Facebook, I got the same message (below).  I'm thinking it could be a Facebook caching issue - I changed my email on Facebook to do this, but it's still finding the old one.  In any case, this is OK because someone can still login, they just have to click the login button.  Can you add:  "Click the Login button below to begin." after the sentence in the red box below?  I think that would clarify that someone can login, they just don't have to register again because they're already on the site.   
![image](https://user-images.githubusercontent.com/78490468/169299541-077d01ef-e6f5-402c-9851-5f617f8e78c8.png)

**Comment by ncaipen** [comment]
Did you actually delete your account within the admin dashboard?  You need to delete your account by signing in as an administrator.  If you deleted the account within your user profile as a homeowner that is likely a soft delete and would be why you can't re-register.

**Comment by PilotFish3447** [comment]
We can close this out.  I'm the only one with the issue and it's related to my admin account, which wouldn't impact users.
