### ISSUE TITLE
Broken Links:  Hinged Patio Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#35]
Door brand model links are broken on Hinged Patio Door page:

![image](https://user-images.githubusercontent.com/78490468/159177850-5980608f-867b-48fb-98d1-9a8001587884.png)

Clear Glass & Grids link is broken:

![image](https://user-images.githubusercontent.com/78490468/159177911-720dff16-07ff-4bb2-aa49-d14845a42150.png)

**Comment by SeanIsAtWork** [comment]
These links have been fixed
