### ISSUE TITLE
Opening previously created Vision Boards loads a blank canvas

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#353]
When I go to open a previously created vision board it wont load and the canvas remains blank. I dont think this is happening for everyone though?

**Comment by ancaipen** [comment]
@SeanIsAtWork - Can you send me the credentials you are using and the vision board that is blank?  I'll see if I can see anything in the database about this.  I was making changes to the vision board the last couple of days and uploading changes for the screen resolution updates and autosave feature.  Its possible if the issue only happened to you, you may have been testing while I was making code changes.

**Comment by SeanIsAtWork** [comment]
It looks like this is happening for me, I have one vision board on my portfolio and just tried to open it but the images arent showing up

**Comment by SeanIsAtWork** [comment]
Actually I'm mistaken, I tried opening up a vision board (titled 4/26 9:54) and it opened up an untitled autosaved board instead.

**Comment by ancaipen** [comment]
@SeanIsAtWork : Is it possible to create a video of what you see or give me the credentials you are using so I can reproduce the issue?

**Comment by ancaipen** [comment]
@SeanIsAtWork : From our meeting last week you had mentioned that this may have been fixed when the titles had been updated to accommodate for special chars.  I'm closing this issue, but if we need to re-open we can.  Thanks!
