### ISSUE TITLE
WTB needs padding at top

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#356]
I logged in and used WTB to set my preferred dealer and the page loads like this.  Please add padding at top. (Chrome 1314x602)
![image](https://user-images.githubusercontent.com/78490468/165534100-26404ab5-b4f9-49d2-af16-e0ca2690c43d.png)

**Comment by SeanIsAtWork** [comment]
This is due to the menu items wrapping, I've extended the maximum width of the top nav right there and this should be back to normal now
