### ISSUE TITLE
WTB - key for icons - text color

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#357]
On the WTB results, there doesn't appear to be a key that explains what the icons are for (ie which one is Platinum, which on is Certified Installer, etc.) On the old site, there's a pop-up over each icon that explains what it is (see third screencap below).  
![image](https://user-images.githubusercontent.com/78490468/165534924-8b0c5bee-4be9-401c-bc75-40de07e0d5bf.png)

![image](https://user-images.githubusercontent.com/78490468/165534681-7b208c3b-e524-4cc4-902f-e1e1d927135a.png)
![image](https://user-images.githubusercontent.com/78490468/165535825-78591b3b-be48-4bd7-b662-29935b8e7478.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - I have fixed this script issue.  I now see the tooltip displaying when you hover over the images above:

![image](https://user-images.githubusercontent.com/43222107/166148843-3373c657-f29c-44bc-bf9e-102bfbcb53e3.png)

**Comment by plaugs** [comment]
Looks good but I am noticing a weird loading glitch the first time it loads:
![issues-tooltip](https://user-images.githubusercontent.com/831625/166241699-469c63d8-e636-4fc4-97c5-65ee99a3ce5c.JPG)

Also, the green text is hard to read. I suggest simply changing it to a lighter color

**Comment by PilotFish3447** [comment]
@ancaipen - I see same glitch as Brian above and agree green text should be changed to white - no reason that text needs to be a different color.

**Comment by ancaipen** [comment]
@plaugs @PilotFish3447 : Take a look now, it looks like the display:none in the css file was being overridden.  I forced this inline in the html and now I'm not seeing that text glitch.  I thought that this was caused by caching because I didn't see it after I loaded the page a few times originally. 

![image](https://user-images.githubusercontent.com/43222107/166691872-d5dbe95b-05f3-4713-bcd0-413dcdbca3f5.png)

**Comment by PilotFish3447** [comment]
Yeah, looks good.  No ghost image anymore.  @plaugs or @SeanIsAtWork - do you want to change the green text to white?  I think it would be more readable.
![image](https://user-images.githubusercontent.com/78490468/166716086-7b03c9af-ecab-4f59-830f-5c4cd2182694.png)
