### ISSUE TITLE
Saved Images instructions could be more clear

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#360]
I think it would be helpful to be more clear in how/where people save images for them to appear on the Vision Board, both on the page and as part of Step 1 in the "How it Works".  Suggest adding:  The ProVia heart icon (use icon) lets you save images throughout the site to your Vision Board here where you can use ....(rest of sentence)  
![image](https://user-images.githubusercontent.com/78490468/165551597-adaee294-a525-4192-9a3e-f89c3d27def9.png)
On the "How it Works" slider, you might want to add a new Step 1:  Click the "heart icon" throughout our site to save your favorite images to your Vision Board repository.
![image](https://user-images.githubusercontent.com/78490468/165553008-06b4b4db-cfff-4290-9a56-3c75efbb1a19.png)

**Comment by jenkline** [comment]
@SeanIsAtWork I made the change under the My Vision Board header. Would you be able to add a step in the How It Works popup as Angie is suggesting?

**Comment by plaugs** [comment]
New gif sent to sean
![hearted](https://user-images.githubusercontent.com/831625/167852023-0ad15539-c21d-47c7-9458-b9d51ff69799.gif)
