### ISSUE TITLE
Images not labeled well enough for Vision Board Filter function

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#361]
When I use the filter to find "stone," image A does not show up in the filtered view. When I filter for "siding," Image B does not show up.
When I filter for "door," I only get one image, whereas I would expect any door-related images (labeled C below) that I clicked on a door page should show up?
![image](https://user-images.githubusercontent.com/78490468/165557653-64c4780b-e740-4a21-ac4f-51da842d9ce5.png)
![image](https://user-images.githubusercontent.com/78490468/165557734-6bf43ac0-f612-45c6-b809-df5ab0656e82.png)

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 I remember @ancaipen mentioning this in one of our earlier calls that it would be possible to mess with the tags/categories of products in the search here but hadnt tried yet

**Comment by PilotFish3447** [comment]
@ancaipen take a look at categories to see if we can filter that way.

**Comment by ancaipen** [comment]
This filter has been updated.  Filter now includes: Product Name, Tags and Categories labels.

![image](https://user-images.githubusercontent.com/43222107/166157269-a71139f3-2195-4be2-8135-60bce8d37ba1.png)

![image](https://user-images.githubusercontent.com/43222107/166157316-5876594b-9a25-4023-b86d-8511aa3c643a.png)

**Comment by jenkline** [comment]
Looks good to me. @SeanIsAtWork is this working for you, too? If so, we could probably close this.

**Comment by SeanIsAtWork** [comment]
@jenkline Works for me!

**Comment by PilotFish3447** [comment]
@jenkline @SeanIsAtWork - this works better, but I think you may still have some images not well enough labeled.  In my testing this image does not show up when you filter for "siding":
![image](https://user-images.githubusercontent.com/78490468/166313591-22de4606-7b6c-4f7e-a120-349ff65e0d9c.png)

**Comment by jenkline** [comment]
@PilotFish3447 None of the Timberbay products have the term "siding" in them. We would probably have to assign "siding" tags to them.

**Comment by jenkline** [comment]
@PilotFish3447 I fixed this. Some of the Timberbay swatches were uncategorized instead of being in the category "Siding." I added them to that category.
