### ISSUE TITLE
Saved images dragged off to oblivion - add instruction?

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#362]
When you drag a saved image onto the Vision Board, I think it's more intuitive for a person to try to drag it back into the saved images rather than to click the X.  But, when you do that, it causes the image to disappear entirely and not go back into the saved images.  Could we add a short description above the Filter box that says:  Drag images to move them to your Vision Board. Click the X on images to return them to your saved folder.  
![image](https://user-images.githubusercontent.com/78490468/165558724-82ca0df4-da70-4c66-8908-e4fd8ac91077.png)

**Comment by jenkline** [comment]
@SeanIsAtWork I was going to add this, but when I went to edit, I don't see a great place to add this without making the image box a little shorter so this can go on top of it. I didn't want to mess with your styling at this point. Could you look at that?

**Comment by SeanIsAtWork** [comment]
@jenkline I should be able to add some text pretty easily and then you can edit it

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 @jenkline  I've added this tip above the search bar

**Comment by jenkline** [comment]
@SeanIsAtWork This looks great to me!
