### ISSUE TITLE
Download feature of Vision Board blocked by Sucuri

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#363]
When I click the Download button on the Vision Board, I get a Sucuri error:
![image](https://user-images.githubusercontent.com/78490468/165559839-748f7f8b-6a00-48e8-8c79-cbefcabe755f.png)
![image](https://user-images.githubusercontent.com/78490468/165559753-a8e32a07-b416-4e2c-a75a-b4f1c09576da.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - I added an exception for this in sucuri please re-test: /wp-content/plugins/provia-myprojects/tmpl/downloadfile.php
