### ISSUE TITLE
Twitter button on Vision Board - add text re: pop-up

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#364]
When I click the Twitter button, it says "Saved," but I don't know what that means.  I would expect it to open a dialogue box to open my Twitter account and save the image there, but it doesn't.  
![image](https://user-images.githubusercontent.com/78490468/165561260-0e9b0776-4193-4f38-81a8-1ec13b91a7d1.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - I tested this issue and for my user I was able to save the vision board and see my new twitter post (see below).  We cannot directly upload images to twitter, but we can share the full image link.  I'm wondering if you tested last week while I was making changes to the auto-save.  Can you test this again and see if it is working as expected?    

![image](https://user-images.githubusercontent.com/43222107/166162536-8bee1467-770f-4ea5-8c42-2569340ed2fc.png)

**Comment by PilotFish3447** [comment]
@ancaipen - I figured out the issue. I had pop-ups blocked.  I think we'll need to add a line of text that says "Pop-ups must be enabled to share to social media" because the error was so tiny (it was a little icon in the URL box) that I missed it the first time.
@jenkline Can you add to the line below at the end: (Pop-ups must be enabled to share to social media.) 
![image](https://user-images.githubusercontent.com/78490468/166312653-688f89f4-6163-4fa6-9a3d-d55d978edcce.png)

**Comment by jenkline** [comment]
@PilotFish3447 Done!

**Comment by ancaipen** [comment]
@PilotFish3447 @jenkline Thanks everyone!  It looks like this issue is closed, if we need to reopen we can.
