### ISSUE TITLE
Edge Cut Tundra Grout Visualizer image color not correct

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#368]
It looks like the same grout color is being displayed for the black and brown grout colors for this product:
![image](https://user-images.githubusercontent.com/78490468/165591923-c45d0177-8b5c-4409-86a9-6d271c9381cd.png)

**Comment by PilotFish3447** [comment]
Add No Grout selection for all Edge Cut.

**Comment by ancaipen** [comment]
This selection and icon have been added back to the grout selector.

![image](https://user-images.githubusercontent.com/43222107/166158359-aac64306-d283-4880-bbbe-54ef6e0aa620.png)

**Comment by ncaipen** [comment]
FYI - I see color change between the brown/black with this product and also double checked and separate images that correspond with the correct colors are also loading on click.
