### ISSUE TITLE
Configurator - responsive issue

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#372]
On iPad, the "Save to My Portfolio" button needs to be fixed for responsive display:
![image](https://user-images.githubusercontent.com/78490468/165623739-70585b9d-b62e-4ecf-b156-df7e0efb0b6b.png)

**Comment by SeanIsAtWork** [comment]
This was built by our IT department, I'll pass this onto them.

**Comment by PilotFish3447** [comment]
This is fixed.  I'm closing it.
