### ISSUE TITLE
Edge Cut Admiral - incorrect image label

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#376]
On the grout selector, the Edge Cut Admiral no grout option has the wrong label - it's marked as white grout, but it should be a "no grout" for this image, similar to what we have for other Edge Cut colors:
![image](https://user-images.githubusercontent.com/78490468/166309340-ed81da78-9912-4c4d-9372-cd65b9fc57cd.png)
It should be labeled like this one:
![image](https://user-images.githubusercontent.com/78490468/166309537-dbcd4b71-62d9-4a79-a9ea-7a75255b3a7f.png)

**Comment by ncaipen** [comment]
This has been corrected.

**Comment by PilotFish3447** [comment]
Thanks!
