### ISSUE TITLE
ProVia Consumer Complaint Policy page outdated links

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#379]
The GuildQuality and Consumer Reports links don't go to any content related to ProVia and when I checked those sites there didn't seem to be a way to get to any ProVia-related content.  Also, the BBB link just shows bad reviews for ProVia.  Everyone knows about BBB, so no need to deliberately send people there.  Let's remove this whole section - it's outdated.
![image](https://user-images.githubusercontent.com/78490468/166484706-ad9f43ab-59f9-4271-9725-d59539b833f5.png)

**Comment by jenkline** [comment]
Done
