### ISSUE TITLE
Mobile menu missing

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#382]
![image](https://user-images.githubusercontent.com/78490468/166488862-5b9f289b-04d9-435a-9c84-6704dc8dd500.png)

**Comment by SeanIsAtWork** [comment]
I think Natalee and Aaron might be deactivating plugins right now to debug an issue, so lots of content is missing from the site right now temporarily

**Comment by PilotFish3447** [comment]
This was only an issue because Elementor had turned off plugins.  Looks good now.
