### ISSUE TITLE
Door Partnerships - responsive design issue, incorrect link

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#383]
These items were not related to Elementor plugins being deactivated.  These are still issues.  
On 1024x768 screen resolution, this drop-down is re-sizing too narrowly:
![image](https://user-images.githubusercontent.com/78490468/166491758-c1efabe5-ad2b-42fc-87f7-0b16b1b10c53.png)
The link below goes to the wrong page - it should go to the Sliding Glass Door page: https://provia.proviaserver-v2.com/doors/sliding-glass-patio-doors/
![image](https://user-images.githubusercontent.com/78490468/166494370-73ca00de-a086-4904-b7ff-3c92bbea4482.png)

**Comment by plaugs** [comment]
This is likely because the plugins are deactivated by the Elementor dev team.

**Comment by PilotFish3447** [comment]
@plaugs  - I removed the item that was caused by the deactivation of the plugins.  Two issues remain above.
