### ISSUE TITLE
Gallery images on my iPhone 8 are not all showing up

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#389]
On my iPhone 8, no matter whether I'm using my home high-speed WIFI, the Verizon network, or the ProVia WIFI, I'm not able to load all of the gallery images. It's almost like they are lazy loading, but some just aren't loading at all. Some will show up later as I'm scrolling. 
![Stone Gallery](https://user-images.githubusercontent.com/104006203/166725880-845e7096-76da-4366-b195-b62ea48c2160.jpg)
![Window Gallery](https://user-images.githubusercontent.com/104006203/166725890-10b18c2c-9aa6-4135-a5f2-594ca24a43dd.jpg)
![Siding Gallery](https://user-images.githubusercontent.com/104006203/166725955-7d769188-05a9-4793-84f6-d88a08a023b8.jpg)

**Comment by jenkline** [comment]
I tried replacing images and that did not help. This is occurring in all product galleries.

**Comment by SeanIsAtWork** [comment]
I noticed this was happening to me last night on my iPhone SE too

**Comment by ncaipen** [comment]
@jenkline @SeanIsAtWork  - Elementor Support requested that we roll back the version of PHP that is running on the server to fix this issue.  I have completed this change.  Can you please test this again using your IPhones?  You may need to clear your cache or view in an incognito window if possible.

**Comment by jenkline** [comment]
@ancaipen @sean I cleared my Safari browsing data and relaunched Safari on my phone, but there are still images not showing up in the various galleries.

**Comment by ncaipen** [comment]
@jenkline - I have temporarily turned off lazy loading.  Can you check this again when you have a chance?

**Comment by jenkline** [comment]
@ncaipen Yes, this is working on my phone now. The pictures come in as I scroll through the slider. Is that different than lazy loading?

**Comment by ncaipen** [comment]
That is what you would see with lazy loading, but I am wondering if the widget already has that functionality since it's a gallery scroll.  I turned lazy loading back on for the site, but excluded lazy loading from W3 Total Cache for the Stone Fireplace Gallery.  Can you check just that gallery and let me know if all the images are still present?  If that works we should just add the no-lazy class to any instances of these scrollers.

**Comment by jenkline** [comment]
@ncaipen This morning everything is loading beautifully for me in the galleries :-)
