### ISSUE TITLE
Broken Links:  Storm Doors page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#39]
Broken links:
![image](https://user-images.githubusercontent.com/78490468/159186387-fab2fd4e-16c8-4c84-9c53-ce7276c4c4e3.png)

![image](https://user-images.githubusercontent.com/78490468/159186419-c6764553-aa1f-4565-b053-976878565f1d.png)

**Comment by SeanIsAtWork** [comment]
Links have been fixed
