### ISSUE TITLE
Door Configurator: Replace Session with configuration details.

### ISSUE THREAD

**Issue by ancaipen** [ancaipen/Provia#397]
I wanted to revisit the highlighted observation you mentioned below from last month. Now that I’m able to save my configurations, this is something I noticed is happening. Any saved configuration takes me back to the very last product I configured. Is there a way to make each one return to the appropriate session? If not, I am wondering how helpful it is that those older configurations link back to the configurator. For my configurations, I changed the door style, glass style (from Inspirations™ to decorative) and color, and all of them go back to the last session only.

Thinking about the below problem we’re having while saving configurations to my portfolio, I wanted to try and voice a thought I had that might be helpful. I want to preface this by saying that the case could very well be that you’ve all already thought this idea through and is not anything new, but I’m hoping that my sending this email will be of some help!

On the Design Center right now we have a button that says “open this door configuration” which opens a popup with a custom configuration. https://provia.proviaserver-v2.com/design-center/#envision

![image](https://user-images.githubusercontent.com/43222107/166912874-4fbb5ec4-5cce-4c48-acf5-d31492fd633b.png)

Mike helped Brian and I make this custom query string to achieve this feature. My thought is that, what if whenever you save a configuration to your portfolio, youre saving a custom query string along with the data that’s already being passed through? This way a user would open the actual configuration they’ve saved instead of the last configuration they left in the given session.

**Comment by ancaipen** [comment]
I added a new field to the api call: config_data.  This field is 5000 characters long.  Lets start there and go ahead and save the config data back to that field and I'll take a look at how we can incorporate it into the front end on the new provia.com site.

**Comment by ancaipen** [comment]
I’ve updated our side; when returning to resume editing a saved image; pass the config data back using:

&cfg=xxxxxx
 
So the three params we need back are:

s (session id)
p (passcode)
cfg (configuration data string).

This should allow seamless saving/editing of these images. 

The update on the design page will be live in 20 minutes or so.

**Comment by ancaipen** [comment]
@jenkline @SeanIsAtWork @plaugs - I have made this change on the site.  I tested this and it appears to be working for me.  Please test and let me know if this is working for the Provia team as well.  Thanks!

*keep in mind: If we have cfg data from a previous save I include it, otherwise it won't be there.  This update will work for any new records saved since Brent's changes have been added*

![image](https://user-images.githubusercontent.com/43222107/167614065-cf950564-52c7-42d6-8042-254720a1c7b6.png)

![image](https://user-images.githubusercontent.com/43222107/167614206-ede8099a-878a-412b-963d-1f08a9c72d25.png)

**Comment by SeanIsAtWork** [comment]
Oh yeah, works for me!! Cool!!!!

**Comment by jenkline** [comment]
This is working for me, too! Awesome!

**Comment by ancaipen** [comment]
Ok great, I'm going to close this item.
