### ISSUE TITLE
Double/rapid clicking images on loaded vision board makes images disappear

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#398]
Loading the board then clicking images (not moving or resizing them) makes them disappear. We noticed this happening on Jerome's computer yesterday. He cleared his browser cache, but I cant replicate this for some reason, both on my admin account and my personal account using gmail.

**Comment by ancaipen** [comment]
@SeanIsAtWork : Would it be possible to capture a video of this happening?  I gave this a quick try and I'm not able to reproduce in chrome, firefox or IE.

**Comment by ancaipen** [comment]
Jerome showed me this, a couple of notes to consider when testing:

1. Jerome's screen resolution was big, update to match for testing.
2. Its possible on the large screen resolution that the double click is dragging it off the canvas.  Add blocking to images so they cannot leave the constraints of the canvas.

**Comment by PilotFish3447** [comment]
@ancaipen  Meeting Recording:
https://us06web.zoom.us/rec/share/rv6Xg81uj5yin0QRzRtz_CaZo9LP4kfuZJAKsuCX53xohmnCUsXXxSi1zVmWds1P.rQzdp4yunyve0G2p

Access Passcode: 6Pb.RikZ

**Comment by SeanIsAtWork** [comment]
@ancaipen just sent this to Jerome to retest. I think it works well having a perimeter on the canvas!

**Comment by SeanIsAtWork** [comment]
@ancaipen Jerome let me know that his images are still disappearing unfortunately :/ We're wondering if, like you said, it might have something to do with his large screen size? We'll just leave this issue open for now and leave it so we can see if employees run into the same issue. Since we'll be able to capture data from them itll help us figure out whats going on here.

**Comment by PilotFish3447** [comment]
@ancaipen @SeanIsAtWork - I re-tested this also - works fine for me.  Can't double click on the images at all or drag them off the canvas.

**Comment by ancaipen** [comment]
@SeanIsAtWork : Ok great, I leave this feature on.  We may need to do a screenshare with him again and see where these images are going.  I also haven't been able to reproduce when I set my screen res really high, but I may need to test on my tv as well?  It could also be a z-index issue?  I could mess with that a bit as well.

**Comment by ancaipen** [comment]
1. Resize the image to a really large size
2. Save the board
3. Hard refresh the page, load the same project 
4. Try to move the really large image and it should disappear

**Comment by PilotFish3447** [comment]
@ancaipen - I followed your steps above and by golly, it did disappear.

**Comment by ancaipen** [comment]
I may have this working now.  I'm not sure why this would make a difference, but I removed the transition css from the close button and now the top image is not disappearing.  Can you try this out on your end and see if it is now working for you as well?  There must be something in the transition of the close button that is messing with the resizing on the largest image and when you click on the image it triggers the close javascript.  

![image](https://user-images.githubusercontent.com/43222107/169032114-e6a48754-c77f-4b0e-8ff8-5bc8311983a6.png)

**Comment by ancaipen** [comment]
I think this maybe an issue with the javascript library?  In some cases it looks like the x overlaps the entire image and when clicked the image goes back to the toolbar in the right.  I think I have this issue fixed.  In some other cases I think the drag/drop is off and the numbers go way too high (see below) and the image is dragged way off the canvas.  The library I use does have a pro version which we could try to purchase and I could post this thread to the community board for help.  I'll keep everyone posted on what I find.

![image](https://user-images.githubusercontent.com/43222107/169283226-c2d7e35a-0c75-4731-b254-02370072ef77.png)

**Comment by ancaipen** [comment]
I have posted this issue to the interact.js chat board for help: https://gitter.im/taye/interact.js

**Comment by ancaipen** [comment]
Hi Everyone, so far the post above isn't yielding any help.  I'm trying other forums, etc for help.  I'll update this once I have more info.
