### ISSUE TITLE
Grout Selector not working

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#400]
Did the grout selector get turned off or is someone working on it?  When I click a thumbnail, it's not pulling up anything.
![image](https://user-images.githubusercontent.com/78490468/167149827-7ba9e63d-cf76-4c64-bd0f-dc4f4875a502.png)

**Comment by ancaipen** [comment]
@PilotFish3447 - Hi Angie, this was me.  I was messing around with code to display the pop-up differently for iframe users.  This has been removed, you may need to clear your cache to reset the javascript.  Thanks!

**Comment by PilotFish3447** [comment]
This looks good.  I'm closing it out.
