### ISSUE TITLE
Text edits to automated email response to contact form

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#403]
Please make the following edits to the automated email response:
1. Change Subject line to:  Thanks for contacting ProVia (remove field for first name insert or fix)
2. Change text in body of email to add this as the first sentence:  We received your inquiry.  A representative... 
![image](https://user-images.githubusercontent.com/78490468/167446219-87d21d14-ed9f-4e64-b23e-bdf56d13b59b.png)

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 Hey Angie, do you remember which contact form you filled out to get this?

**Comment by SeanIsAtWork** [comment]
@ancaipen Ok this should be fixed now

**Comment by PilotFish3447** [comment]
Looks good.  I'm closing it out.
