### ISSUE TITLE
Door/Window Configurator - Go to/Return to My Portfolio

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#408]
When someone configures a door or window with the configurator and saves the final product selection, there's no button or link to navigate to the My Portfolio section to see their image there.  Can Brent add this - maybe right below the Saved button below?
![image](https://user-images.githubusercontent.com/78490468/167926005-7e9087fb-45d7-40ec-9fc4-a7b59862aaa8.png)

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 @jenkline Hmm good question, I'm sure they could add a link underneath easily. Should we word that in a specific way?

**Comment by PilotFish3447** [comment]
@SeanIsAtWork @jenkline - How about:  VIEW IN MY PORTFOLIO

**Comment by jenkline** [comment]
@PilotFish3447 @SeanIsAtWork Would that make sense still if a dealer was using it through entryLINK and maybe didn't have a portfolio? If they clicked on it, I'm assuming that would take them to the main page where they could figure out that they need to sign up. Or, would it make sense to have a button that says, "Create a My Portfolio account?"

**Comment by PilotFish3447** [comment]
@jenkline @SeanIsAtWork -- If a user clicks on the current My Portfolio button and they aren't already logged in or don't have an account, it automatically displays a pop-up for them to either log-in or set up an account.  So I think that just linking to the MyPortfolio page in the same way that the home page button does would achieve the same thing and work for both homeowners and dealers.  (ie below, I clicked the My Portfolio button (1) and the pop-up registration box came up (2) 
![image](https://user-images.githubusercontent.com/78490468/167933223-664733fa-5894-49e7-8a73-09fb61b6649e.png)

**Comment by PilotFish3447** [comment]
Sean sent request to Brent via email 5/13/22 asking:  Could we make this link target=”_blank” so it opens in a new tab? And change the url to https://provia.proviaserver-v2.com/my-portfolio/#configurations. 

Brent responded 5/13/22:  Next rollout

**Comment by SeanIsAtWork** [comment]
This has been added by IT
