### ISSUE TITLE
Wordpress/Elementor stripping forward slash \ from Design Center and My Portfolio stylesheets

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#410]
![image](https://user-images.githubusercontent.com/95431522/168095302-1954aa66-c7d3-475e-a30b-9d20bfce14af.png)
Every once and awhile I'll go on the design center and see that the \ on a line of css ( e.g. content:'\f2ea' ) is stripped from the content property on ::before and ::after pseudo tags and I'll have to fix it manually. The result before its fixed is the above screenshot where the content is a bunch of characters instead of the unicode for the given Font Awesome icon that I wrote in. 

Have either of you seen this using wordpress before @ancaipen @ncaipen ? The css is from an elementor stylesheet that I edit on the design center page, its quite lengthy so I dont include it in the global stylesheet. I've never experienced this with the big global stylesheet we use which utilizes the same method of adding icons to the content property of a pseudo tag. 

Definitely low on the priority list but just wondering if theres something I'm missing. Idek why this would be happening in the first place either.

**Comment by ncaipen** [comment]
Have you tried regenerating the Elementor CSS when you see this has happened (but before you fix)?  Elementor -> Tools -> Regenerate CSS & Data.  Another option we might want to try would be to take these few styles that are impacted and group them directly with the plugin so they are separate from Elementor.

**Comment by SeanIsAtWork** [comment]
@ncaipen Yeah, I think it'd be a good idea to put the vision board css in the stylesheet instead of residing in elementor. This also happens on the portfolio page, but its on TI Wishlist stuff, so I'll try regenerating the css next time in that case. Thanks!
