### ISSUE TITLE
Where to Buy isnt showing results

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#411]
Results dont show up
![image](https://user-images.githubusercontent.com/95431522/168140106-c683c605-53db-4f0d-b876-4e39434b8bd9.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork : This has been fixed.  Take a look and let me know if this is now working as expected.  Thanks!

**Comment by SeanIsAtWork** [comment]
@ancaipen Perfect. Thanks Aaron.
