### ISSUE TITLE
Pressing load more button doesnt show images

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#414]
![image](https://user-images.githubusercontent.com/95431522/168617783-6f353671-af43-4107-97ea-19cef4fe74f2.png)
The products load but the images dont show up. 

Probably related to #389 ? Originally #389 relates to mobile devices but this is happening on desktop

**Comment by ancaipen** [comment]
@SeanIsAtWork : We are working with elementor in this and they think this is related to amount of plugins we are using in tandem with the lazy loading.  We will keep you posted on this

**Comment by SeanIsAtWork** [comment]
@ncaipen @ncaipen So in this case with the AJAX function it looks like pressing load more isnt applying the **.loaded** class to any of the images. This is with lazy loading turned on. I'm not sure if these classes are being applied by elementor or woocommerce or wordpress. 

This is irrelevant with lazy loading turned off though, earlier this morning those two classes werent being applied to images.

**Comment by ancaipen** [comment]
@jenkline @SeanIsAtWork - I'm closing this item since we have decided to keep lazy loading turned off.  If we need to reopen we can.
