### ISSUE TITLE
Old page that should be removed? 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#415]
The BrightEdge site audit found a stone and grout visualizer page that didn't have meta tags, and when I looked at it, I think it might be an older version of what became the final grout visualizer page?  
Here's the page the site audit found: https://provia.proviaserver-v2.com/stone/stone-and-grout-color-visualizer/
Here's the actual grout visualizer page:  https://provia.proviaserver-v2.com/stone/grout-visualizer/

Is the first page being used for something?  Is it intended to be public and visible on Google?  If not, you should un-publish it or delete it.  If it is intended to be indexed for Google, I can add SEO meta tags.

**Comment by jenkline** [comment]
@SeanIsAtWork It looks like you created that first link in March, but the second link (the one we're using on the site) was created in January. Do you remember why that first link was created? I'm assuming it's okay to at least unpublish it, but just wanted to make sure.

**Comment by SeanIsAtWork** [comment]
@jenkline I mightve just made a new one not thinking about the one that had already existed. I just turned it into a draft since we're not using it
