### ISSUE TITLE
Change entry link to one word on entrylink login page

### ISSUE THREAD

**Issue by SeanIsAtWork** [ancaipen/Provia#417]
![6283da6d5cab6](https://user-images.githubusercontent.com/95431522/169299593-db55ab6a-9b6c-4299-90d5-9bbf82ec0bca.png)

This space in "entry link" just needs deleted

**Comment by ancaipen** [comment]
@SeanIsAtWork : This has been updated.

![image](https://user-images.githubusercontent.com/43222107/169304785-865a27c9-9c9e-4b45-b6d2-4455c3050c5e.png)
