### ISSUE TITLE
Go Live Checklist

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#419]
0. Update DNS as needed

*only for local DNS*
- update name servers
ns1037278175.a2dns.com
ns1037278176.a2dns.com

1. PRE GO-LIVE BACKUPS: BACKUP SITE!!!

**CREATE MANUAL DATABASE BACKUP**
- Database export
- Amazon S3 archive latest snapshot

2. Site link update: run database updates

//RUN SCRIPT as NEEDED
https://provia.proviaserver-v2.com/wp-json/provia/v1/provia_admin/updatelinks/

SET @Find = 'proviasandbox.oxbowserver.com', 
SET @Replace = 'provia.proviaserver-v2.com';

update `wp_posts` 
set post_content=REPLACE(post_content, @Find, @Replace)
where post_content like ('%' + @Find + '%')

update `wp_options` 
set option_value=REPLACE(option_value, @Find, @Replace);

update `wp_postmeta` 
set meta_value=REPLACE(meta_value, @Find, @Replace); 

update `wp_posts` 
set guid=REPLACE(guid, @Find, @Replace);

//find orphaned post meta
SELECT * 
FROM wp_postmeta as pm 
LEFT JOIN wp_posts as p
  ON pm.post_id = p.ID
WHERE p.ID IS NULL

3. update site licenses

- associate elementor to the new site URL
https://my.elementor.com/login
u: ncaipen@enetohio.com
p: 2UPM4BeSBKcFtcp

--clear elementor cache
WP Admin -> Tools -> General
	- Regenerate CSS & Data
	- Sync Library
	- replace URL tab, update URL

--update ultimate member subscription URL

--update elementor "the plus" subscription URL

--update ti project subscription URL
	- reactivate plugin
	
4. Update robots.txt to remove line:

Disallow: /

5. Update iframe links in code to point to correct urls.  Current code is using test URLs 
	- File Location: C:\SITES\polysort\provia\provia_v3\Provia\provia-iframe\scripts\iframe
	- provia-iframe plugin
	
6. Update provia-api plugin code to point to proper url: search for provia.proviaserver-v2.com
	- provia-api.php
	- search all custom code for hardcoded values and update
	- where to buy
	- etc

7. Update/enable google analytics for new site

8. Update DNS, Sucuri firewall settings
		- Whitelist URL: /wp-content/plugins/provia-wheretobuy/ajax/wtb.php
		- Allow other POSTs for plugins. - these should be added for test domain, need to be updated for prod.
		
9. Group walkthrough after go-live to ensure that everything looks ok.
		- Test all pages with custom plugins
		- Test the IFRAMEs

10. Just a reminder that the Facebook/Twitter buttons are turned off on the Vision Board while employees are testing. Make live before launch.

11. Provision backup server and copy/paste site copy script to new server.  Work through any issues and get backup/restore working properly.

12. Test contact forms:
-- https://provia.proviaserver-v2.com/contact/
-- https://provia.proviaserver-v2.com/why-its-great-to-partner-with-provia/door-partnerships/ (and other product forms)
-- https://provia.proviaserver-v2.com/warranty/
-- https://provia.proviaserver-v2.com/iframe-help-contact/
 
13. Remove Feedback Survey, rename "Bugs" tab to "Feedback".

14. Natalee needs to send Angie the updated XML sitemap once site goes live so she can update Google Search Console.

15. Set up 301 redirects.

16. Update Facebook API to point to domain provia.com  

17. Test iframes once new site is live

https://www.jdwindowsanddoors.com/aeris-window-line/
https://www.jdwindowsanddoors.com/signet/

https://www.daytondoorsales.com/residential/entry-and-patio-doors/heritage-series.php
https://www.daytondoorsales.com/residential/entry-and-patio-doors/endure-series.php

https://www.fullarmorwindowsanddoors.com/legacy/
https://www.fullarmorwindowsanddoors.com/deluxe/

https://www.herschbergerwindows.com/embarq-doors
https://www.herschbergerwindows.com/aspect-windows

https://www.hunterdoor.com/entry-doors/provia-doors/provia-patio-doors/designer-hinged-patio-door/
https://www.hunterdoor.com/entry-doors/provia-doors/provia-storm-doors/duraguard-storm-door/

**Comment by ancaipen** [comment]
@PilotFish3447 

This is a good idea to track.  I have updated this issue as a go-live checklist that I have been compiling over the last month or so (see below) including your item about facebook.  I will plan to put anything else here we need in the meantime

**Comment by SeanIsAtWork** [comment]
I'm seeing that the iframes on all 5 dealer websites listed above are not adjusting the height to the respective content, and the header is showing despite it being hidden in the iframe stylesheet. This is also the case on the pilotfish site https://www.pilotfishseo.com/iframe-old-test/, but on provia.com/iframe it looks as it should.
