### ISSUE TITLE
Sitewide Gallery Caption Naming Mechanism

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#42]
Gallery caption naming mechanism is inconsistent throughout the site. 

![image](https://user-images.githubusercontent.com/101943507/159187359-a3c0e7fe-ce02-4084-b96d-cc36ac430f2e.png)

**Comment by SeanIsAtWork** [comment]
Captions for these images (not saveable products, which is a different system entirely) are dependent on the title given to the image and can be changed as we see them. In the case of this and one other vintage stained glass style the names have been updated.
