### ISSUE TITLE
Text not lining up properly on Factory Stain blog, link issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#426]
On this page: https://provia.proviaserver-v2.com/blog/factory-stained-glazed-painted-doors/
1. Text doesn't line up at the top:
![image](https://user-images.githubusercontent.com/78490468/170111238-f3cbe590-c502-40de-9c35-6d5f919c103c.png)
2. The two anchor links below don't go to the sections intended:
![image](https://user-images.githubusercontent.com/78490468/170111682-a916412f-7a48-470a-9b54-453174b2342b.png)
3. The anchor links below don't go to the sections intended:
![image](https://user-images.githubusercontent.com/78490468/170111972-548ddd80-b5b3-4d06-bbf3-e074378b7994.png)
4. Legacy steel link below should go to Legacy page:  https://provia.proviaserver-v2.com/doors/entry-doors/legacy/
![image](https://user-images.githubusercontent.com/78490468/170112298-595b734f-82d6-4a69-8d7a-8e036bb9de99.png)
5. Add padding on left side for mobile from top of page down to the Stained Front Entry and Hinged Patio Doors header:
![image](https://user-images.githubusercontent.com/78490468/170114128-aabc36fa-ccd8-4308-848c-f024de9cc5dd.png)
![image](https://user-images.githubusercontent.com/78490468/170114228-0fc79fd7-9db3-4ca7-af95-333ab61e1931.png)

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 great, think I've got everything now

**Comment by PilotFish3447** [comment]
looks good.
