### ISSUE TITLE
Search styling on mobile

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#427]
Is it possible to style the Search function on mobile so the text isn't so big so you can see the whole word or phrase you type in to search?
![image](https://user-images.githubusercontent.com/78490468/170117434-39092534-a11c-47d1-b0e1-d5d6ae92d91b.png)

**Comment by SeanIsAtWork** [comment]
@PilotFish3447 good catch, i changed the font size and padding

**Comment by PilotFish3447** [comment]
looks good.
