### ISSUE TITLE
Regenerating CSS needed at random intervals 

### ISSUE THREAD

**Issue by plaugs** [ancaipen/Provia#428]
Current site menu css is not loading causing the menu to display incorrectly.
![Capture](https://user-images.githubusercontent.com/831625/170267018-7482848a-1e9d-4f23-bee7-917b5e4be26d.JPG)
![Capture2](https://user-images.githubusercontent.com/831625/170267026-5e1f1d72-c6da-4f13-96f5-9133cb072d0e.JPG)

**Comment by ancaipen** [comment]
@ncaipen - Have you seen this before?  I know you can re-generate the css files, but maybe we can do this on a schedule?

**Comment by ncaipen** [comment]
I am not aware of a way to regenerate automatically unless that's something you can do on your end, @ancaipen.  It is normal to have to regenerate the Elementor css as you are making changes to the site.

**Comment by SeanIsAtWork** [comment]
Just noting that I just had to regenerate the CSS again after we noticed the search bar not formatting correctly

**Comment by SeanIsAtWork** [comment]
Had to regenerate css again this morning
