### ISSUE TITLE
Image Galleries Extend Beyond Intended Content

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#43]
Most image galleries on the development site have an arrow that allows you to click past the intended selection of swatches and throughout an entire gallery of images not relevant to the context. 

For example, on the Popular Finish Options gallery, when you click a swatch that leads you to the gallery and use the arrow (circled below) to scroll through the images, it keeps going on to irrelevant images, such as the one example image seen below. 

 
![image](https://user-images.githubusercontent.com/101943507/159187472-342e3665-62f3-4d01-997c-81fdf8d80850.png)

![image](https://user-images.githubusercontent.com/101943507/159187476-37ccc738-1682-4547-aecf-fc9ae28363c7.png)

 

This same issue is present in the Exterior Paint Finish Options module: 
 
![image](https://user-images.githubusercontent.com/101943507/159187481-6e73ed46-2ca8-4734-9c5b-98b66c27dd7e.png)

**Comment by SeanIsAtWork** [comment]
This is an issue we're aware of, we're disabling the lightbox navigation for products for now since we cant sort through a specific category in specific instances.
