### ISSUE TITLE
Cancel Google Search on Friday 6/3

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#430]
This is for Jerome and Brian:  Per our collective research earlier this month, we found that you manage the account for the Google Search function on the current site.  The new site doesn't use Google Search, so cancel your account before your next billing cycle - I believe the next charge will be on 6/6, so cancel on Friday.

**Comment by plaugs** [comment]
After literally looking for an hour. I finally think I found where to manage this. I am baffled that things related to Google are so hard to find.  Does any of you know how to manage the payment to cancel automatically? I am setting a reminder regardless to cancel this.
