### ISSUE TITLE
Spanish Moss palette is missing from grout visualizer

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#434]
This palette can be previewed on this page: https://www.provia.com/stone/palettes/. Can this please be added to the grout visualizer page as well (https://www.provia.com/stone/grout-visualizer/)? A customer was looking for a specific profile today, referred to his catalog, found the Spanish Moss palette, and realized that it was missing from the grout configurator.

**Comment by ancaipen** [comment]
@jenkline : Just to make sure, is this something you want us or Sean to take care of?  If it is us you can just assign myself or Natalee and we can take a look.  Thanks!

**Comment by ncaipen** [comment]
@SeanIsAtWork - Can you create the Spanish Moss tab that you want to be used for this?  I will add the visualizer links once the tab has been created how you want it.

**Comment by ncaipen** [comment]
I added the Grout Selector product IDs within the Spanish Moss palette.  These popups should work once the Spanish Moss tab is added to the Grout Selector page.

**Comment by jenkline** [comment]
@SeanIsAtWork @ncaipen There is already a Spanish Moss tab created for the stone palettes page. Not sure if that is helpful or not, but it should be a template.

**Comment by SeanIsAtWork** [comment]
@ncaipen @jenkline I just added the spanish moss tab to the grout visualizer page

**Comment by ncaipen** [comment]
Great, thanks!  I think this should be complete.  Please recheck and let me know if you need anything else.

**Comment by jenkline** [comment]
@ncaipen @SeanIsAtWork Thank you both!
