### ISSUE TITLE
iframes not displaying correctly on some sites

### ISSUE THREAD

**Issue by jenkline** [ancaipen/Provia#439]
I know we talked about this on our last call before Aaron and Natalee went on vacation, but I wanted to put this here as well. From what Brian can tell, it looks like for some customers, the iframe URLs are still the old ones, and we are having to generate new iframes for some customers. Here is an example of one I am working with where the new page is coming in, but not displaying correctly: https://www.abedoors.com/doors/product/provia/deluxe-storm-doors.cfm#. Brian generated a new code for them, which they are trying now. Brian also suggested removing all references to the old iframe code and resizer, so hopefully that will work.

**Comment by ancaipen** [comment]
Hi Jen,

This is a weird one.  I see some jQuery errors on this one (see below).  It also does look like the iframe is resizing ok for me?     

![image](https://user-images.githubusercontent.com/43222107/174784546-30787dd3-5edd-430a-909f-bebfeb0b8a39.png)

I checked out the source and it appears that some bad jQuery code has been added manually to site that could be causing the error above?  I

![image](https://user-images.githubusercontent.com/43222107/174785054-be3dbe69-ad56-4c87-85b8-b418695179d5.png)

If a site has jQuery errors on it already that may cause issues with the code.  I would recommend working with the dealer's developer to fix the jQuery errors above first and see if that makes a difference.  With that said, it did look like the iframe code was working as expected for me in Firefox and Chrome.

**Comment by jenkline** [comment]
I worked with their web guy to regenerate a new iframe code, and Brian advised me to tell them to replace any resizer code they had. That worked, and everything looks good now. There are still issues with some of the other iframes on the list Angie sent of a few customers who are utilizing iframes: 

https://www.fullarmorwindowsanddoors.com/legacy/
https://www.fullarmorwindowsanddoors.com/deluxe/

https://www.herschbergerwindows.com/embarq-doors
https://www.herschbergerwindows.com/aspect-windows

https://www.hunterdoor.com/entry-doors/provia-doors/provia-patio-doors/designer-hinged-patio-door/
https://www.hunterdoor.com/entry-doors/provia-doors/provia-storm-doors/duraguard-storm-door/
