### ISSUE TITLE
Window-Related Video Module Captions Getting Cut Off

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#44]
In all browsers 1280 W and smaller Window-Related Video module captions are not resizing properly: 

 
![image](https://user-images.githubusercontent.com/101943507/159187587-aaa8bd61-7918-400d-8f4f-9d0645a88038.png)

![image](https://user-images.githubusercontent.com/101943507/159187566-54193c8c-bb8e-41be-aa3d-95998bd82319.png)

**Comment by SeanIsAtWork** [comment]
Fixed globally
