### ISSUE TITLE
Entry Link: Lead Form

### ISSUE THREAD

**Issue by ancaipen** [ancaipen/Provia#443]
Create Lead form as a plugin to capture and send leads to entry link via POST.  Below is the form created in elementor that can be used as a starting point.  

https://www.provia.com/why-its-great-to-partner-with-provia/door-partnerships/ 

![image](https://user-images.githubusercontent.com/43222107/178306652-f132b090-3d89-44fa-9aa1-7e2a276a28b7.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork @jenkline @ncaipen - I completed the 1st version of this form on a test page on the production site: 

https://www.provia.com/test-lead-capture/?test=15 

For reference, I'm posting this information to the EntryLink webservice URL we used on the old where to buy page here: https://entrylink.provia.com/entrylink/leads.asmx.  I see the leads are saved successfully in our database and entry link.  

![image](https://user-images.githubusercontent.com/43222107/180865925-c7409bb3-de0d-4f11-a518-6501135d6bc3.png)

Can you all test this and let me know if it is functioning as expected and you are seeing the data come through to entry link?  If everything is working, let me know @SeanIsAtWork if you want to style or Natalee and can also do this.  Thanks!  

![image](https://user-images.githubusercontent.com/43222107/180864044-7a8a9e71-5a9f-4709-9c35-fe1e2a875773.png)

**Comment by SeanIsAtWork** [comment]
@ancaipen looks like if you add the class .provia-form to the form element the styles should be automatically applied.

**Comment by ancaipen** [comment]
@SeanIsAtWork - Perfect, this has been added!

**Comment by ancaipen** [comment]
@SeanIsAtWork - Also there is a thank you div that is displayed after submission of the form, but you can't see it due to the formatting on the page.  Let me know what text you want to display here:

![image](https://user-images.githubusercontent.com/43222107/180867581-b91cd7df-2a6e-4454-803d-6784d81d58ef.png)
