### ISSUE TITLE
Windows: Module Text is Not Centered

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#45]
**All screens 1024 x 768 and smaller, including mobile and tablet devices:** 

-----------------------

**“Visit our window gallery … ” text is not centered.** 

Example:
https://provia.proviaserver-v2.com/windows/internal-blinds/ 
![image](https://user-images.githubusercontent.com/101943507/159187665-d2e63564-69d1-4056-8dbb-484cfd3cd463.png)

-----------------------

https://provia.proviaserver-v2.com/windows/brands/aeris/ 

**“Aeris wood-clad windows … “ text is not centered.** 

![image](https://user-images.githubusercontent.com/101943507/159187686-b3945e42-3d47-4a44-9438-a46453c301c9.png)

-----------------------

**“Horizontal sliding windows … “ text not centered:** 

https://provia.proviaserver-v2.com/windows/slider/ 

![image](https://user-images.githubusercontent.com/101943507/159187731-0b19a9bc-06ef-4485-a18f-ebd1f927bd11.png)

**Comment by SeanIsAtWork** [comment]
Left aligned text in these instances has been centered
