### ISSUE TITLE
Windows: Ecolite Content Module Not Sizing Properly

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#46]
All browsers 1024 x 768 and on iPad Vertical

1.	On https://provia.proviaserver-v2.com/windows/brands/ecolite/ module below is not sizing properly. 

![image](https://user-images.githubusercontent.com/101943507/159187840-c1df492e-975f-4c03-a93c-bbf3b531077e.png)

Text is squeezed into a thin column. 

![image](https://user-images.githubusercontent.com/101943507/159187846-91daafe8-ad57-4bcd-9b20-0738a19b34fc.png)

**Comment by SeanIsAtWork** [comment]
Width of content has been fixed
