### ISSUE TITLE
Windows: Resizing Creates Overlapping Green Rule and Text

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#48]
**1024 x 768 Screen Size: Green horizontal rule in Featured Products module is in wrong position on the following pages:** 

https://provia.proviaserver-v2.com/windows/classic-colonial
https://provia.proviaserver-v2.com/windows/modern

![image](https://user-images.githubusercontent.com/101943507/159187924-0e58cb9c-a74c-43a8-ac63-50962de65f5d.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed
