### ISSUE TITLE
Windows: Victorian Window Styles Image Not Sizing Properly

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#49]
**On  https://provia.proviaserver-v2.com/windows/bay-bow/ Victorian Window Styles image is not sizing properly:** 

**Note: This is true for all sizes smaller than 1024 x 768, including mobile and tablet devices.** 

![image](https://user-images.githubusercontent.com/101943507/159187931-7a04866c-a988-4ac9-a74b-ed0dff5a2f87.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed
