### ISSUE TITLE
Windows: Pages with No Left Margin (1280 x 960)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#50]
**1280 x 960 Screen Size: Many of the modules do not have a left column margin on the following pages:** 

https://provia.proviaserver-v2.com/windows/gallery 
https://provia.proviaserver-v2.com/windows/craftsman 
https://provia.proviaserver-v2.com/windows/victorian 
https://provia.proviaserver-v2.com/windows/classic-colonial
https://provia.proviaserver-v2.com/windows/modern 

**Examples:**  

![image](https://user-images.githubusercontent.com/101943507/159188121-26521be9-1c80-4017-9664-d0f5663f12af.png)

![image](https://user-images.githubusercontent.com/101943507/159188129-8f798890-2692-4f59-86f9-6370a4ed4fa3.png)

![image](https://user-images.githubusercontent.com/101943507/159188138-224da3f3-fbb1-4d6e-9fe8-9742861c3d2a.png)

![image](https://user-images.githubusercontent.com/101943507/159188140-d241cc80-d866-44e6-b08a-ae2a8c83c4de.png)

**Comment by SeanIsAtWork** [comment]
These have been fixed
