### ISSUE TITLE
Door Stain & Paint Options page CSS issues 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#53]
Tabs below need to be centered for smaller screen resolutions (below is 1024x768 on Chrome 100)
![image](https://user-images.githubusercontent.com/78490468/159187809-8d0283da-24ea-4f05-aa36-9bb9c81b08ee.png)

Too much white space between sections in smaller screen resolutions (1024x768 and smaller)
![image](https://user-images.githubusercontent.com/78490468/159187869-f21bcc19-fe82-499b-8c4b-d57c2da1ca62.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed
