### ISSUE TITLE
Windows: Images Not Sizing Properly (1024 x 768)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#54]
1024 x 768 Screen Size: Images not sizing properly. 

https://provia.proviaserver-v2.com/windows/privacy-glass/ 

Thumbnail images are not sizing properly: 

![image](https://user-images.githubusercontent.com/101943507/159188536-967165e5-eaa4-4fb6-97fa-6c04a35ca23a.png)

**Comment by SeanIsAtWork** [comment]
These have been fixed
