### ISSUE TITLE
Door Panel Styles CSS issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#57]
Tabs need to be centered for smaller screen sizes (1024x768 and smaller):
![image](https://user-images.githubusercontent.com/78490468/159188611-9413f9ed-9d3d-4fd8-af56-3fbb5338aabc.png)

Too much white space between modules on smaller screen sizes (1024x768 and smaller):
![image](https://user-images.githubusercontent.com/78490468/159188636-d389e0f7-084d-4ef8-a31f-66990086dcbe.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed globally for all instances of tabs like this being used
