### ISSUE TITLE
Windows: Space Below Explore Modern Module (iPhone and Android)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#58]
**iPhone and Android Vertical Orientation: There is a large white space below all instances of the Explore Modern module:** 

![image](https://user-images.githubusercontent.com/101943507/159189033-b37a3692-52a4-406a-a380-36dd00128255.png)

**Comment by SeanIsAtWork** [comment]
Margin/padding of the whole architectural styles section, probably just leave it for now
