### ISSUE TITLE
Windows: Window Technology Header Getting Cut Off (iPhone)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#61]
iPhone Vertical Orientation

https://provia.proviaserver-v2.com/windows/technology/ 

Header is getting cut off: 

![image](https://user-images.githubusercontent.com/101943507/159189565-0cd61923-569d-4875-a75d-757c74d9aafd.png)

**Comment by SeanIsAtWork** [comment]
This has been fixed
