### ISSUE TITLE
Windows: Window Glass Gallery Overlapping Text (iPhone)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#62]
iPhone Horizontal Orientation

https://provia.proviaserver-v2.com/windows/gallery/#glass 

Overlapping text: 

![image](https://user-images.githubusercontent.com/101943507/159189602-82db35ca-841f-443f-8894-2d90921286db.png)

**Comment by SeanIsAtWork** [comment]
I cant replicate this on my iphone even when flipping between vertical and horizontal
