### ISSUE TITLE
Windows: Window Brands Module Positioning, Logo Cut Off (iPhone)

### ISSUE THREAD

**Issue by PilotFishHK** [ancaipen/Provia#65]
**iPhone Horizontal Orientation: Module Position off center, logo cut off.**

https://provia.proviaserver-v2.com/windows/vinyl/ 

Windows are not centered and columns are narrow / squeezing text. Happening on iPad Vertical version as well.  

![image](https://user-images.githubusercontent.com/101943507/159189761-3a260f31-28fc-41fb-a384-15c7dc4250ca.png)

![image](https://user-images.githubusercontent.com/101943507/159189762-3e88c5d7-fe45-4a68-98b8-3e039d521381.png)

-------------------------

**Provia logo is getting cut off:** 

![image](https://user-images.githubusercontent.com/101943507/159189796-02934b7e-5937-4fef-b42c-cf8a24497851.png)

**Comment by SeanIsAtWork** [comment]
All fixed
