### ISSUE TITLE
Door Stained Glass page CSS issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#71]
Hamburger menu displays for desktop screen resolutions and doesn't work:
![image](https://user-images.githubusercontent.com/78490468/159189829-3e2fdb9d-278c-4948-a5c4-766fab0f112f.png)

Too much white space between some sections, particularly in smaller screen resolutions.
![image](https://user-images.githubusercontent.com/78490468/159189935-04751481-58c9-47b2-9e05-e134e7a7c920.png)

![image](https://user-images.githubusercontent.com/78490468/159190167-11521a9b-b178-41f2-810d-abe14e914255.png)

Color palette images cut off in iPhone and Samsung:
![image](https://user-images.githubusercontent.com/78490468/159189979-8dac3ee4-2a8e-4b7e-a122-bb3f20726e3a.png)

Stained glass images cut off in iPhone and Samsung:
![image](https://user-images.githubusercontent.com/78490468/159190004-7ea655ad-fb39-4806-b49b-7080756b8666.png)

Scroll dots overlap text on mobile device:
![image](https://user-images.githubusercontent.com/78490468/159190248-adb4c6a3-69d3-4971-a652-7cbac3d88ffb.png)

![image](https://user-images.githubusercontent.com/78490468/159190262-7df1e9da-e03a-4948-9d7a-50fdcc313ad9.png)

Stained glass door images don't re-size for landscape orientation for mobile phones:
![image](https://user-images.githubusercontent.com/78490468/159190067-9ee13c08-af3e-4d53-94e5-1cafc15ece46.png)

Palette colors don't show up on landscape orientation for mobile phones:
![image](https://user-images.githubusercontent.com/78490468/159190117-56fb3064-7f69-43bd-a5fe-445fe05fe453.png)

**Comment by SeanIsAtWork** [comment]
All issues fixed
