### ISSUE TITLE
Design Center: Save All Pallettes 

### ISSUE THREAD

**Issue by ancaipen** [ancaipen/Provia#8]
Give the user the ability to save all palettes at once to a user's wish list.  **Sean to include any additional details.

**Comment by ancaipen** [comment]
For example, the 'Save All' button to allow saving to default project.  We can at least use My Projects code to save all items in bulk.     

![image](https://user-images.githubusercontent.com/43222107/154507255-53bb148a-e704-41e4-bfe5-d8fc6e82fdf1.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork - Hi Sean, I have completed the coding needed for this functionality.  We now inject a new javascript file: https://provia.proviaserver-v2.com/wp-content/plugins/provia-api/scripts/provia-api.js on the public site that allows palettes to be saved in bulk.  Below are the changes you will need to make in order for this functionality to work.  If you have any questions just let me know!  

1. A new script has been created to handle the bulk operations of adding many products to a wishlist at one time.  In order for this script to work we must assign the proper class names needed.  To start, you must assign the class: provia-saveall to the button you wish to trigger the adding of a palette.  Here is an example of what this would look like:

![image](https://user-images.githubusercontent.com/43222107/163841844-0db1b9cc-4fa1-41be-a54e-84ad3c89d67e.png)

This will enable the javascript behind the scenes to collect all images in the associated div and add all elements to the signed-in user's wishlist.

2. Once we find that a button with the class: provia-saveall has been clicked, we then look for the closest div with the class name: palette-container. 

![image](https://user-images.githubusercontent.com/43222107/163842168-95aa0e30-31dc-4225-9a80-50f536129bba.png)

Our code will then find all items within the palette-container div that contain the class: quick_view and a valid data-product-id assigned (see below).  
 
![image](https://user-images.githubusercontent.com/43222107/163842381-7ed6d47a-e56f-4ee7-b112-f5a2f6cc44e7.png)

3. To test and make sure that this operation worked you should see the output in the console log in a browser and upon refresh see all images highlighted with a selected 'heart' image.

![image](https://user-images.githubusercontent.com/43222107/163844011-8726f043-1264-4099-9095-bc6d66907f55.png)

![image](https://user-images.githubusercontent.com/43222107/163843225-326d9331-ba64-40af-8bfe-bc217b41405b.png)

**Comment by SeanIsAtWork** [comment]
@ancaipen hey Aaron, this looks great! Thanks for all the clear instructions, however I can only add a class to the parent element of a button and not the actual <a> tag. See screenshot 
![image](https://user-images.githubusercontent.com/95431522/163856232-a8b2ba11-c9f7-4951-aea6-3ea397bed253.png)
Would you be able to work with this?

**Comment by ancaipen** [comment]
@SeanIsAtWork - Hi Sean, the code also works on the class: .elementor-button-link and .provia-saveall, but it does need to be on the <a href=""> to pick up the button click.  In your example above it looks like you are using the class: elementor-button as well.  I have added that too just in case.  If you have an example page where this is not working let me know and I'll debug and make the necessary changes.  Thanks!

**Comment by SeanIsAtWork** [comment]
@ancaipen Hey Aaron, I'm trying this on the Design Center but it doesnt seem to be working. Upon clicking the save all button it does look like the page is loading the script and then refreshes but it doesnt like all the images. I personally have a few liked on, for example, the warm and welcoming palette, but not sure if that would make a difference.

**Comment by SeanIsAtWork** [comment]
@ancaipen I think whats happening now is that anytime I click a link (at least on the design center) the page tries to load this script. Elementor uses the class .elementor-button-link on all buttons by default.

**Comment by ancaipen** [comment]
@SeanIsAtWork - I found this bug, there were issues on the other items in the carosel which have since been fixed.  I tested this with my account and it now appears to be working.

Before clicking on 3rd panel:

![image](https://user-images.githubusercontent.com/43222107/164066590-66432a0e-bedc-4d3c-8318-d7f7f44d08ad.png)

After clicking on 3rd panel (all images are added to wishlist):

![image](https://user-images.githubusercontent.com/43222107/164066729-7ec0cc00-7b2b-4683-9faf-411c5036bee9.png)

![image](https://user-images.githubusercontent.com/43222107/164066973-2b833de8-5018-43b5-966e-6dea4453083a.png)

**Comment by SeanIsAtWork** [comment]
When i try this it seems like the last product (bottom right) doesnt get picked up and liked, although all the others do. TO give some more context that may be important, on my account I typically have like 2 or 3 products from each palette saved to my portfolio already.

**Comment by SeanIsAtWork** [comment]
@ancaipen also any other buttons on the page are still activating this script and reloading the page, you can test this by clicking any of the configurator buttons at the top of the page or the "how it works" button above my vision boards to test this. 

Can your script look for an a tag who is a child of a .provia-saveall div instead of the a tag with a class of .provia-saveall? Unless you know of a way to add a link to the actual a tag.

**Comment by ancaipen** [comment]
@SeanIsAtWork - Thanks for this.  I found the bug with the last item and I updated the button click logic a bit to be more exclusive to only elements within the .provia-saveall class.  Take a look now and let me know if that is working better.  Thanks!

![image](https://user-images.githubusercontent.com/43222107/164074625-522b045b-cdec-4d82-995e-e45def74ba57.png)

**Comment by SeanIsAtWork** [comment]
@ancaipen Aw yeah, looks like the save all function works! But any button that has .elementor-button-link is still reloading the page,

**Comment by ancaipen** [comment]
@SeanIsAtWork - I updated this logic to make it more exact so you shouldn't see the page reload now for other links.

**Comment by ancaipen** [comment]
@SeanIsAtWork - I'm closing this item to get it off the board.  This should be resolved, but if find any issues go ahead an re-open with your testing results.  Thanks!

**Comment by SeanIsAtWork** [comment]
@ancaipen Hey Aaron, would you be able to add the background product into this save all function as well? I have a class called .palette-background-product on a parent element that the product is in. 
![image](https://user-images.githubusercontent.com/95431522/169101737-68836e11-29e5-4f75-b625-e05b1ab2d2c1.png)
![image](https://user-images.githubusercontent.com/95431522/169101755-5a575baa-b5ac-498f-9e26-7052ebf18af4.png)

**Comment by ancaipen** [comment]
@SeanIsAtWork - Sorry I didn't realize I never updated this open item.  This update has been added for a while.  Here is a screenshot of what it looks like for the oxbow account on the homepage.  

![image](https://user-images.githubusercontent.com/43222107/181634211-91b3d5f3-79f1-42b1-be95-814bdb99a354.png)
