### ISSUE TITLE
Broken Links on Door Hardware page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#82]
Broken links - check text links under each tab for the types of hardware (Emtek, Mortise, Trilennium, etc):
![image](https://user-images.githubusercontent.com/78490468/159198517-a73f9a8c-4db6-4ec7-af87-03900be9b54e.png)

![image](https://user-images.githubusercontent.com/78490468/159198559-5903787f-9cc5-4b04-a174-9a359b776e71.png)

Typo:  Missing space between Entry Door and Hardware:
![image](https://user-images.githubusercontent.com/78490468/159198648-ab4dd0f9-b1a5-4d03-b0e8-4754e1afaf82.png)

**Comment by SeanIsAtWork** [comment]
All fixed
