### ISSUE TITLE
Main Doors page issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#87]
These buttons don't link to anything, should link to following pages:
https://provia.proviaserver-v2.com/doors/entry-doors/
https://provia.proviaserver-v2.com/doors/patio-doors/
https://provia.proviaserver-v2.com/doors/storm-doors/

![image](https://user-images.githubusercontent.com/78490468/159271579-18f1d047-c55b-47e7-8533-4e620abe32e3.png)

This section doesn't line up on the left with the headline from the section above it: 
![image](https://user-images.githubusercontent.com/78490468/159271991-084d7e30-7201-4c5e-917d-9309dcf1d9cd.png)

The blog article section isn't styled the same way as the rest of the site:
![image](https://user-images.githubusercontent.com/78490468/159272463-6ccdf9f2-cc1d-4cc0-90ae-3083bb73a609.png)

![image](https://user-images.githubusercontent.com/78490468/159272530-93fb835c-fb6f-4a47-9453-315738e6fd66.png)

Video section is not styled the same way as the rest of the site:
![image](https://user-images.githubusercontent.com/78490468/159272702-dcc37c41-e45a-40d1-8eaf-aaad403411a7.png)

![image](https://user-images.githubusercontent.com/78490468/159272786-af0e9ae1-94a5-4778-8850-4417d73eb900.png)

A lot of extra space between the top image and main text on mobile and 1024x768:
![image](https://user-images.githubusercontent.com/78490468/159273177-ca80d9d3-afd8-468a-a28d-beebaf8d3912.png)
![image](https://user-images.githubusercontent.com/78490468/159275665-caaeb32f-8344-475f-afd8-cfbb66ce1090.png)

A lot of white space between sections in mobile and 1024x768:
![image](https://user-images.githubusercontent.com/78490468/159273518-3872e621-e215-45d8-956d-f3accacc7467.png)
 
In 1024x768, the hairline rule doesn't extend through the length of the box:
![image](https://user-images.githubusercontent.com/78490468/159275967-7a1de26b-d16c-4c0f-bb9f-53b56a7d74a0.png)

**Comment by SeanIsAtWork** [comment]
Any fixes that arent styling related (issue #104) have been fixed
