### ISSUE TITLE
Fiberglass Doors page issues - page not styled

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#88]
Page design not complete/consistent with rest of site.

Text at top not styled same as other pages (see example 2nd screenshot below from Entry Door page) 
![image](https://user-images.githubusercontent.com/78490468/159278859-192c090f-0d3b-45f6-8940-c00a6ac57300.png)

![image](https://user-images.githubusercontent.com/78490468/159279030-115ed5bf-531e-415a-ae45-e475f01235e7.png)

Hairline rules, door brands section not styled.

Will review for responsive once page has been styled.

**Comment by SeanIsAtWork** [comment]
Refer to issue #104
