### ISSUE TITLE
Broken Link - Steel Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#89]
Broken links:

![image](https://user-images.githubusercontent.com/78490468/159279573-f310483b-b456-4bb2-9fcb-f762a1f869a8.png)

![image](https://user-images.githubusercontent.com/78490468/159279730-6556e6a1-984f-43fd-bc94-af5572ca1cbf.png)

**Comment by SeanIsAtWork** [comment]
Link fixed
