### ISSUE TITLE
Steel door page - incomplete styling

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#90]
In various screen resolutions in Chrome and on Edge, the steel doors page does not appear to be styled like the rest of the site:
![image](https://user-images.githubusercontent.com/78490468/159285937-dfdd35d1-22e0-40f3-a076-735a6e5b3ee7.png)

![image](https://user-images.githubusercontent.com/78490468/159286030-6b77292a-e070-4430-b0d9-279c9db9238c.png)

![image](https://user-images.githubusercontent.com/78490468/159286146-dc9b054c-948a-44da-9372-3fd038885ac3.png)

Will re-visit to check responsive design once page styling is complete.

**Comment by SeanIsAtWork** [comment]
Refer to issue #104
