### ISSUE TITLE
Broken links:  Vinyl door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#91]
Broken links:
![image](https://user-images.githubusercontent.com/78490468/159286482-e43a13c8-de09-4aa3-ab0e-67c4c4d96b68.png)

![image](https://user-images.githubusercontent.com/78490468/159286588-7a09bf3c-cfde-4e17-a08f-1e040ac8ab52.png)

![image](https://user-images.githubusercontent.com/78490468/159286688-5d358b53-4604-46a6-9b51-8d58022f00cd.png)

**Comment by SeanIsAtWork** [comment]
Links all fixed
