### ISSUE TITLE
Vinyl Patio Doors - CSS issues

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#92]
https://provia.proviaserver-v2.com/doors/vinyl-doors/

Missing image at top of page:
![image](https://user-images.githubusercontent.com/78490468/159287041-c4b52411-1d4e-4ab3-90e8-d2d76f3f5618.png)

A lot of extra white space between sections in 1024x768 and smaller resolutions:
![image](https://user-images.githubusercontent.com/78490468/159287580-dfa0d5c1-bd30-4565-b74b-c1025bdcbf10.png)

![image](https://user-images.githubusercontent.com/78490468/159288354-4bfa61e7-080b-46ef-b014-9b724f1a6371.png)

**Comment by SeanIsAtWork** [comment]
Header image added and white space adjusted globally
