### ISSUE TITLE
Broken Links: Signet Door page

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#95]
Broken links:
![image](https://user-images.githubusercontent.com/78490468/159303041-39bfb3c2-0543-4d33-befa-77ac1cc75639.png)

![image](https://user-images.githubusercontent.com/78490468/159303504-dd57e701-bfb8-49f2-acd6-76d3986a83f7.png)

**Comment by SeanIsAtWork** [comment]
All fixed
