### ISSUE TITLE
Entry Door brand pages CSS issues 

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#97]
These comments apply to the Embarq, Signet, Legacy and Heritage pages:

A lot of extra white space between sections, particularly in smaller screen sizes:
![image](https://user-images.githubusercontent.com/78490468/159305473-de7d3a00-7590-407e-aea2-8635b2690084.png)

On Legacy Steel page and Heritage page, center tabs for finish colors in mobile sizes:

![image](https://user-images.githubusercontent.com/78490468/159305689-6304a4e2-4f8b-4c00-acf0-b87c05e51f1a.png)

**Comment by SeanIsAtWork** [comment]
White space has been minimized globally and tabs have been centered
