### ISSUE TITLE
Broken Links:  Storm Door pages

### ISSUE THREAD

**Issue by PilotFish3447** [ancaipen/Provia#99]
Broken Links on all the storm door pages:
https://provia.proviaserver-v2.com/doors/storm-doors/spectrum/
https://provia.proviaserver-v2.com/doors/storm-doors/decorator/
https://provia.proviaserver-v2.com/doors/storm-doors/deluxe/
https://provia.proviaserver-v2.com/doors/storm-doors/duraguard/
https://provia.proviaserver-v2.com/doors/storm-doors/superview/

Clear Glass & Grids is broken; Stained Glass and Privacy Glass links need to be updated to include trailing /.

![image](https://user-images.githubusercontent.com/78490468/159336550-58055dc1-0730-4880-97ce-cc648fa4a1a2.png)

![image](https://user-images.githubusercontent.com/78490468/159334529-ccdd56fc-8e0a-45ed-ae2c-4235df29e471.png)

**Comment by SeanIsAtWork** [comment]
Links have been fixed
